// Normalized, deployment-safe projection of
// thoughtseed-labs/00-meta/work-object-registry.v1.json.
// Source inventory paths and operational payloads are intentionally omitted.

export type RawAlias = readonly [value: string, namespace: string];
export type RawSapling = readonly [
  workId: string,
  name: string,
  promotionState: 'proof-only' | 'supervised-branch',
  tenantStatus: 'canonical' | 'canonical-parent' | 'unresolved',
  tenantId: string | null,
  provenance: readonly string[],
  linkedWorkIds?: readonly string[],
  aliases?: readonly RawAlias[],
  commercialReuse?: 'white-labelable',
];
export type RawProgram = readonly [
  workId: string,
  name: string,
  programKind: 'client' | 'company' | 'capability' | 'operations',
  lifecycle: 'proposed' | 'approved' | 'executing' | 'verifying' | 'complete' | 'retired',
  tenantStatus: 'canonical' | 'documented-not-runtime-verified' | 'not-applicable' | 'unresolved',
  tenantId: string | null,
  provenance: readonly string[],
  accountId?: string,
  linkedWorkIds?: readonly string[],
  overlay?: 'paused',
  commercialReuse?: 'white-labelable',
];
export type RawHistoricalProduct = readonly [
  canonicalId: string,
  name: string,
  status: 'archived' | 'completed' | 'white-labelable' | 'paused',
  linkedCanonicalId: string | null,
  source: string,
];
export type RawClassificationReview = readonly [
  canonicalId: string,
  source: string,
  needed: string,
];

export const RAW_SAPLINGS: readonly RawSapling[] = [
  ['sapling:cambium', 'Cambium', 'supervised-branch', 'canonical', 'cambium', ['vault:00-meta/entity-registry.md', 'vault:40-products/cambium/product-overview.md'], ['program:cambium-operating-fabric']],
  ['sapling:dlock', 'DLOCK', 'proof-only', 'unresolved', null, ['repo:thoughtseed-labs/lockwell-portal', 'site:https://dlock-lp.vercel.app/', 'cambium:docs/plans/product-branches/dlock.md'], undefined, [['dlock', 'brand-alias'], ['Lockwell', 'legacy-repo-name']]],
  ['sapling:fitcheck', 'Fitcheck', 'supervised-branch', 'canonical-parent', 'cambium', ['repo:fitcheck-landing/README.md', 'cambium:docs/plans/product-branches/fitcheck.md'], undefined, [['FitCheck', 'legacy-product-name'], ['getfitcheck', 'brand-alias']]],
  ['sapling:iverif', 'IVerif', 'proof-only', 'unresolved', null, ['cambium:docs/plans/product-branches/iverif.md']],
  ['sapling:vantyx', 'Vantyx', 'supervised-branch', 'unresolved', null, ['cambium:docs/plans/product-branches/vantyx.md', 'repo:Panaroma-Webapp']],
  ['sapling:vibrasonix', 'Vibrasonix', 'proof-only', 'unresolved', null, ['vault:40-products/02-vibrasonix/product-overview.md']],
  ['sapling:fmrl', 'FMRL', 'proof-only', 'unresolved', null, ['vault:40-products/15-fmrl/product-overview.md']],
  ['sapling:whatslegal', 'WhatsLegal', 'proof-only', 'unresolved', null, ['vault:40-products/16-whatslegal/product-overview.md']],
  ['sapling:effort-glyph', 'Effort Glyph', 'proof-only', 'unresolved', null, ['vault:40-products/19-effort-glyph/README.md']],
  ['sapling:parkarea', 'ParkArea Product', 'proof-only', 'unresolved', null, ['vault:40-products/parkarea/product-overview.md'], ['branch:parkarea']],
  ['sapling:tirak', 'Tirak Product', 'proof-only', 'unresolved', null, ['vault:40-products/tirak/product-overview.md'], ['branch:tirak']],
  ['sapling:whspr', 'WHSPR', 'proof-only', 'unresolved', null, ['vault:40-products/whspr/product-overview.md']],
  ['sapling:seedforge', 'SeedForge', 'proof-only', 'unresolved', null, ['vault:00-meta/entity-registry.md', 'vault:40-products/seedforge/product-overview.md'], ['program:teamforge-control-plane'], [['Seedforge', 'vault-product-name'], ['SeedForge', 'founder-view-name']]],
  ['sapling:10869-space', '10869.space', 'supervised-branch', 'unresolved', null, ['repo:10869', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md']],
  ['sapling:hostscale', 'HostScale', 'proof-only', 'unresolved', null, ['repo:hostscalev0', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md'], ['branch:co-property'], undefined, 'white-labelable'],
  ['sapling:nimbus-gate', 'Nimbus Gate', 'proof-only', 'unresolved', null, ['repo:Coproperty/nimbus-gate', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md']],
  ['sapling:wanderfruit', 'WanderFruit', 'proof-only', 'unresolved', null, ['repo:Coproperty/wanderfruit-docs', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md']],
  ['sapling:klear-karma', 'Klear Karma', 'supervised-branch', 'unresolved', null, ['repo:Sheshiyer/klear-karma', 'repo:klear-karma.kkv2-admin-panel', 'repo:klear-karma.kkv2-klear-karma-rn', 'repo:klear-karma.klear-karma-website-v2', 'repo:Sheshiyer/Klearkarma-wiki', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json']],
  ['sapling:rasa', 'Rasa', 'supervised-branch', 'unresolved', null, ['repo:monthlymealprep', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md']],
  ['sapling:agentfount', 'AgentFount', 'proof-only', 'unresolved', null, ['repo:rssfeedscrapper', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md']],
];

export const RAW_PROGRAMS: readonly RawProgram[] = [
  ['branch:airdronauts-panorama-viewer-delivery', 'Airdronauts Panorama Viewer Delivery', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/airdronauts-productions/project-brief.md'], 'airdronauts-productions'],
  ['branch:axtech', 'Axtech', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/axtech/project-brief.md'], 'axdis-group'],
  ['branch:axtech-erp', 'Axtech ERP', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/axtech/erp/project-brief.md'], 'axdis-group'],
  ['branch:brightme', 'Brightme', 'client', 'retired', 'unresolved', null, ['vault:60-client-ecosystem/brightme/project-brief.md'], 'brightme', ['historical-product:brightme'], undefined, 'white-labelable'],
  ['branch:dorix', 'Dorix', 'client', 'retired', 'unresolved', null, ['vault:60-client-ecosystem/dorix/project-brief.md'], 'dorix'],
  ['branch:heyzack', 'HeyZack', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/project-brief.md', 'repo:Heyzack-ai/Heyzack-Email-Templates', 'repo:Sheshiyer/heyzack-dashboard', 'repo:Sheshiyer/heyzack-launchboom-wiki-v0.2', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'heyzack'],
  ['branch:heyzack-zackai', 'HeyZack ZackAI', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/zackai/project-brief.md'], 'heyzack'],
  ['branch:heyzack-crm', 'HeyZack CRM', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/crm/project-brief.md', 'repo:Heyzack-ai/PartnerCRMPortal-docs/apps/partner-docs/content/crm', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'heyzack'],
  ['branch:heyzack-estimate', 'HeyZack Estimate', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/estimate/project-brief.md', 'repo:HeyZack-Domotique/estimate-web', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'heyzack'],
  ['branch:heyzack-partner-portal', 'HeyZack Partner Portal', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/partner-portal/project-brief.md', 'repo:Heyzack-ai/PartnerCRMPortal-docs/apps/partner-docs/content/partner', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'heyzack'],
  ['branch:heyzack-customer-portal', 'HeyZack Customer Portal', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/customer-portal/project-brief.md'], 'heyzack'],
  ['branch:heyzack-panel-app', 'HeyZack Panel App', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/panel-app/project-brief.md'], 'heyzack'],
  ['branch:heyzack-landing', 'HeyZack Landing', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/landing/project-brief.md'], 'heyzack'],
  ['branch:heyzack-tooling', 'HeyZack Tooling', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/tooling/project-brief.md', 'repo:Heyzack-ai/tuya-react-native', 'repo:Sheshiyer/brochure-py-heyzack', 'repo:Sheshiyer/email-engine-heyzack', 'repo:Sheshiyer/heyzack-design-token-system', 'repo:Sheshiyer/heyzack-miniapp-design-systems', 'repo:Sheshiyer/products-list-heyzack-gen', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'heyzack'],
  ['branch:heyzack-proposal', 'HeyZack Proposal', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/proposal/project-brief.md', 'repo:HeyZack-Domotique/heyzack-vinci-proposal', 'repo:Sheshiyer/heyzack-builder-pitch-experience', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'heyzack'],
  ['branch:heyzack-veloren-cee-ai', 'Veloren CEE AI', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/heyzack/veloren-cee-ai/project-brief.md'], 'heyzack'],
  ['branch:instal', 'Instal', 'client', 'retired', 'unresolved', null, ['vault:60-client-ecosystem/instal/project-brief.md'], 'instal', ['historical-product:instal'], undefined, 'white-labelable'],
  ['branch:mathis', 'Mathis Portal', 'client', 'approved', 'documented-not-runtime-verified', null, ['vault:60-client-ecosystem/mathis/project-brief.md', 'vault:60-client-ecosystem/mathis/tenant.json'], 'mathis'],
  ['branch:newsense', 'Newsense', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/newsense/project-brief.md', 'repo:Sheshiyer/newsense', 'repo:Sheshiyer/newsense-launch', 'repo:Sheshiyer/newsense-spatial', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'newsense'],
  ['branch:parkarea', 'ParkArea Client Delivery', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/parkarea/project-brief.md', 'repo:parkarea.parkarea-aleph', 'repo:parkarea.wiki'], 'parkarea', ['sapling:parkarea']],
  ['branch:pongotrasteros', 'Pongotrasteros', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/pongotrasteros/project-brief.md'], 'pongotrasteros'],
  ['branch:symphonics', 'Symphonics', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/symphonics/project-brief.md', 'repo:Sheshiyer/workforce-automation-app-symphonics', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'symphonics'],
  ['branch:sandboxlife', 'SandBoxLife', 'client', 'approved', 'unresolved', null, ['vault:60-client-ecosystem/valore-ventures/project-brief.md', 'repo:Valoreventures/landing-page-v0.1', 'repo:Valoreventures/sandbox-beta', 'repo:Valoreventures/sandboxlife-alpha', 'repo:Valoreventures/sandboxlife-api', 'repo:Valoreventures/sblchat', 'repo:Sheshiyer/sandboxlife-v2', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'valore-ventures', undefined, 'paused'],
  ['branch:safvr-landing-page', 'SAFVR Landing Page', 'client', 'complete', 'unresolved', null, ['repo:SAFVR-SG/Landingpage2.0', 'cambium:docs/project-management/project-r2-mapping-proposals.md'], 'safvr'],
  ['branch:thaleos', 'Thaleos', 'client', 'complete', 'unresolved', null, ['vault:60-client-ecosystem/thaleos/project-brief.md'], 'thaleos', ['historical-product:thaleos']],
  ['branch:tirak', 'Tirak Client Partnership', 'client', 'executing', 'unresolved', null, ['vault:60-client-ecosystem/tirak/project-brief.md', 'repo:pineappleinnovationlabs/rork-tirak--companion-marketplace-in-thailand', 'repo:pineappleinnovationlabs/tirak-admin-command-center', 'repo:Sheshiyer/tirak-backend-alpha01', 'repo:Sheshiyer/tirak-mobile-app-v2', 'repo:Sheshiyer/tirak-website-v1', 'repo:Sheshiyer/wikiv2-tirakapp', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'tirak', ['sapling:tirak']],
  ['branch:wattconnect', 'WattConnect', 'client', 'complete', 'unresolved', null, ['vault:60-client-ecosystem/wattconnect/project-brief.md'], 'wattconnect', ['historical-product:wattconnect']],
  ['branch:wegrid-ai', 'Wegrid.ai', 'client', 'retired', 'unresolved', null, ['vault:60-client-ecosystem/wegrid-ai/project-brief.md'], 'wegrid', ['historical-product:wegrid']],
  ['branch:bwssb', 'BWSSB', 'client', 'proposed', 'unresolved', null, ['vault:60-client-ecosystem/spaceblanket-ai/bwssb/project-brief.md'], 'spaceblanket-ai'],
  ['branch:insight-realtors-legal-advisors', 'Insight Realtors and Legal Advisors', 'client', 'approved', 'unresolved', null, ['repo:Insightreality', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md'], 'insight-realtors-legal-advisors'],
  ['branch:kacima', 'Kācima', 'client', 'executing', 'unresolved', null, ['repo:Kacima', 'repo:Sheshiyer/kacima-new', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'kacima'],
  ['branch:kristudios', 'Kristudios', 'client', 'proposed', 'unresolved', null, ['repo:Sheshiyer/kristudios-heritage', 'repo:Sheshiyer/kristudios-space', 'repo:Sheshiyer/kristudios-v2-web', 'repo:Sheshiyer/kristudios-wiki', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md'], 'kristudios'],
  ['branch:earthy-munchy', 'Earthy Munchy', 'client', 'proposed', 'unresolved', null, ['repo:earthy-munchy', 'repo:Sheshiyer/coming-soon-earthymunchy', 'repo:Sheshiyer/earthy-munchy-beta-launch', 'repo:Sheshiyer/earthymunchy-alpha', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'yamuna-foods'],
  ['branch:harsh-truths', 'Harsh Truths', 'client', 'approved', 'unresolved', null, ['repo:synchronized-universe-blog', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md'], 'harshita'],
  ['branch:wtfmedia', 'WTF Media Workspace', 'client', 'proposed', 'unresolved', null, ['repo:wtfmedia', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md'], 'wtf-podcast'],
  ['branch:valmark', 'Valmark', 'client', 'proposed', 'unresolved', null, ['repo:ratan-pitch', 'repo:ratandevelopers', 'repo:Sheshiyer/Akshara-coauthor', 'repo:Sheshiyer/ratandevelopers-property-coauthor', 'repo:Sheshiyer/valmark-cocreate', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'valmark'],
  ['branch:co-property', 'Co.Property', 'client', 'executing', 'unresolved', null, ['repo:Sheshiyer/copropertyspace', 'repo:Sheshiyer/dashboard-0.1-coproperty', 'repo:Sheshiyer/v0-co-property', 'repo:Sheshiyer/v0-coproperty-checklist', 'repo:Sheshiyer/v0-coproperty-edu', 'repo:Sheshiyer/wiki-coproperty-v1', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'co-property', ['sapling:hostscale']],
  ['branch:ashwinsheth-marina-one-mumbai', 'Marina One — Mumbai Panorama Viewer', 'client', 'executing', 'unresolved', null, ['repo:ashwinsheth-group/panaroma-v2', 'repo:Sheshiyer/panorama-viewer-marina-one', 'repo:Sheshiyer/marina-one-v2-preview', 'repo:Sheshiyer/panorama-viewer-marina-beta', 'repo:Raheman-08/panorama-viewer-marina', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'ashwin-sheth-group'],
  ['branch:ashwinsheth-marina-one-bangalore', 'Marina One — Bangalore Panorama Viewer', 'client', 'executing', 'unresolved', null, ['repo:ashwinsheth-group/marina-one-KA/web', 'repo:Sheshiyer/marina1-k', 'repo:Sheshiyer/skyline-viewer-ashwin-sheth-group', 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], 'ashwin-sheth-group'],
  ['program:cambium-operating-fabric', 'Cambium Operating Fabric', 'operations', 'verifying', 'canonical', 'cambium', ['cambium:docs/architecture/cambium-operating-fabric.md'], undefined, ['sapling:cambium']],
  ['program:teamforge-control-plane', 'TeamForge Cloudflare Control Plane', 'capability', 'executing', 'not-applicable', null, ['vault:00-meta/system-of-records.md', 'repo:team-forge-ts'], undefined, ['sapling:seedforge']],
  ['program:temperance-hermes', 'Hermes and Temperance Execution Plane', 'operations', 'executing', 'not-applicable', null, ['vault:00-meta/system-of-records.md', 'repo:Sheshiyer/temperance_engine', 'repo:Sheshiyer/hermes-aws-ts', 'repo:Sheshiyer/temperance_engine_landing_page', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json']],
  ['program:plexus', 'Plexus Work Coordination', 'capability', 'executing', 'not-applicable', null, ['vault:00-meta/system-of-records.md', 'repo:plexus-ts']],
  ['program:skill-clusters', 'Skill Clusters', 'capability', 'executing', 'not-applicable', null, ['repo:Sheshiyer/skill-clusters', 'repo:manifest-skill-cluster', 'repo:Sheshiyer/motionsites-skills', 'repo:Sheshiyer/professional-headshot-suite', 'repo:Sheshiyer/readme-skill', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json']],
  ['program:snow-gloves-os', 'Snow Gloves OS', 'capability', 'executing', 'unresolved', null, ['cambium:docs/plans/product-branches/snow-gloves-os.md', 'repo:Sheshiyer/snow-gloves-os']],
  ['program:thoughtseed-vault', 'Thoughtseed Labs Vault', 'company', 'executing', 'not-applicable', null, ['vault:00-meta/system-of-records.md', 'repo:Sheshiyer/thoughtseed-labs', 'repo:Sheshiyer/thoughtseed-vault', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json']],
  ['program:meristem-brand-system', 'Meristem Brand System', 'capability', 'executing', 'not-applicable', null, ['repo:brandmint-v2', 'repo:Sheshiyer/brandmint-oracle-aleph', 'repo:Sheshiyer/motionsites-skills', 'vault:00-meta/system-of-records.md', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], undefined, ['program:thoughtseed-brand-atlas']],
  ['program:hdilint', 'HDILINT', 'capability', 'executing', 'not-applicable', null, ['repo:HDILINT-backend-aleph']],
  ['program:explee-capabilities', 'Explee Capability Pack', 'capability', 'executing', 'not-applicable', null, ['repo:explee-skills', 'repo:Sheshiyer/professional-headshot-suite', 'repo:Sheshiyer/readme-skill', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json']],
  ['program:engineering-orchestration', 'Engineering Orchestration', 'capability', 'executing', 'not-applicable', null, ['repo:github-next-wave-orchestrator', 'repo:swarm-architect-skill']],
  ['program:operator-utilities', 'Operator Utilities', 'capability', 'executing', 'not-applicable', null, ['repo:gram-cli', 'repo:reddit-cli', 'repo:Sheshiyer/raycast-extensions', 'repo:Sheshiyer/readme-skill', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json']],
  ['program:company-website', 'Thoughtseed Company Website', 'company', 'executing', 'not-applicable', null, ['repo:thoughtseed/ThoughtseedOS-Site', 'repo:thoughtseed/thoughtseedlabs-web', 'repo:Sheshiyer/website', 'pages:thoughtseed-os-site', 'vault:10-brand-essence/public-website-snapshot.md', 'vault:40-products/digital-platforms/company-website/technical-implementation/README.md', 'cambium:docs/project-management/github-repository-mapping-action-queue.v1.json'], undefined, ['program:thoughtseed-brand-atlas']],
  ['program:paperclip-retired', 'Paperclip Retired Execution Plane', 'operations', 'retired', 'not-applicable', null, ['vault:00-meta/system-of-records.md', 'repo:thoughtseed-paperclip']],
  ['program:thoughtseed-brand-atlas', 'Thoughtseed Brand Atlas', 'company', 'executing', 'not-applicable', null, ['repo:thoughtseed-brand-atlas', 'vault:10-brand-essence/visual-identity-2026-08/README.md'], undefined, ['program:company-website', 'program:meristem-brand-system']],
];

export const RAW_HISTORICAL_PRODUCTS: readonly RawHistoricalProduct[] = [
  ['historical-product:bezly', 'Bezly', 'archived', null, 'vault:40-products/01-bezly/product-overview.md'],
  ['historical-product:senseplay', 'Senseplay', 'archived', null, 'vault:40-products/03-senseplay/product-overview.md'],
  ['historical-product:axtech', 'Axtech Product View', 'archived', 'branch:axtech', 'vault:40-products/04-axtech/product-overview.md'],
  ['historical-product:wegrid', 'Wegrid Product View', 'archived', 'branch:wegrid-ai', 'vault:40-products/05-wegrid/product-overview.md'],
  ['historical-product:thaleos', 'Thaleos Product View', 'completed', 'branch:thaleos', 'vault:40-products/06-thaleos/product-overview.md'],
  ['historical-product:wattconnect', 'WattConnect Product View', 'completed', 'branch:wattconnect', 'vault:40-products/07-wattconnect/product-overview.md'],
  ['historical-product:youblock', 'YouBlock', 'archived', null, 'vault:40-products/08-youblock/product-overview.md'],
  ['historical-product:tokenofme', 'TokenOfMe', 'archived', null, 'vault:40-products/09-tokenofme/product-overview.md'],
  ['historical-product:brightme', 'Brightme Product View', 'white-labelable', 'branch:brightme', 'vault:40-products/10-brightme/product-overview.md'],
  ['historical-product:instal', 'Instal Product View', 'white-labelable', 'branch:instal', 'vault:40-products/11-instal/product-overview.md'],
  ['historical-product:ask-abraham', 'Ask Abraham', 'archived', null, 'vault:40-products/12-ask-abraham/product-overview.md'],
  ['historical-product:uvyield', 'UVYield', 'archived', null, 'vault:40-products/13-uvyield/product-overview.md'],
  ['historical-product:maximum-protocol', 'Maximum Protocol', 'archived', null, 'vault:40-products/14-maximum-protocol/product-overview.md'],
  ['historical-product:qapt', 'QAPT', 'archived', null, 'vault:40-products/17-qapt/product-overview.md'],
  ['historical-product:brandbook-ai', 'Brandbook AI', 'archived', null, 'vault:40-products/brandbook-ai/product-overview.md'],
  ['historical-product:triage-ai', 'Triage AI', 'archived', null, 'vault:40-products/triage-ai/product-overview.md'],
  ['historical-product:ui-system', 'UI System', 'archived', null, 'vault:40-products/ui-system/product-overview.md'],
  ['historical-product:newsletter', 'Newsletter', 'archived', null, 'vault:40-products/newsletter/product-overview.md'],
  ['historical-product:podcasts', 'Podcasts', 'paused', null, 'vault:40-products/podcasts/concepts/podcast-concepts-overview.md'],
  ['historical-product:pineapple-labs', 'Pineapple Labs', 'archived', null, 'cambium:docs/evidence/2026-08-06-classification-needed-findings.md'],
];

export const RAW_CLASSIFICATION_REVIEW: readonly RawClassificationReview[] = [];

export const RAW_OPERATIONAL_GAP_WORK_IDS = [
  'sapling:cambium',
  'sapling:dlock',
  'sapling:fitcheck',
  'sapling:iverif',
  'sapling:vantyx',
  'sapling:vibrasonix',
  'sapling:fmrl',
  'sapling:whatslegal',
  'sapling:effort-glyph',
  'sapling:parkarea',
  'sapling:tirak',
  'sapling:whspr',
  'sapling:seedforge',
  'branch:airdronauts-panorama-viewer-delivery',
  'branch:axtech',
  'branch:axtech-erp',
  'branch:heyzack',
  'branch:heyzack-zackai',
  'branch:heyzack-crm',
  'branch:heyzack-estimate',
  'branch:heyzack-partner-portal',
  'branch:heyzack-customer-portal',
  'branch:heyzack-panel-app',
  'branch:heyzack-landing',
  'branch:heyzack-tooling',
  'branch:heyzack-proposal',
  'branch:heyzack-veloren-cee-ai',
  'branch:mathis',
  'branch:newsense',
  'branch:parkarea',
  'branch:pongotrasteros',
  'branch:symphonics',
  'branch:sandboxlife',
  'branch:tirak',
  'branch:bwssb',
  'program:cambium-operating-fabric',
  'program:teamforge-control-plane',
  'program:temperance-hermes',
  'program:plexus',
  'program:skill-clusters',
  'program:snow-gloves-os',
  'program:thoughtseed-vault',
  'program:meristem-brand-system',
  'program:hdilint',
  'program:explee-capabilities',
  'program:engineering-orchestration',
  'program:operator-utilities',
  'program:company-website',
  'program:thoughtseed-brand-atlas',
] as const;
