// Generated by apps/portfolio-cartographer/scripts/generate-portfolio-root-map.mjs. Do not edit.
export const PORTFOLIO_ROOT_MAP_DIGEST = "20af5f2b3e194c67f1e19f9acc477cdfc51654876d75b310f4541998a8a576dc" as const;
export const TRYAMBAKAM_PROJECTS = {
  "723": {
    "path": "tryambakam-noesis/723",
    "status": "awaiting-ingestion"
  },
  "10869x77": {
    "path": "tryambakam-noesis/10869x77",
    "status": "awaiting-ingestion"
  },
  "aleph1319xwebsite": {
    "path": "tryambakam-noesis/aleph1319xwebsite",
    "status": "awaiting-ingestion"
  },
  "aletheos-morphic-nexus": {
    "path": "tryambakam-noesis/aletheos-morphic-nexus",
    "status": "awaiting-ingestion"
  },
  "astrolens": {
    "path": "tryambakam-noesis/astrolens",
    "status": "awaiting-ingestion"
  },
  "astrolens-website": {
    "path": "tryambakam-noesis/astrolens-website",
    "status": "awaiting-ingestion"
  },
  "brand-docs-final": {
    "path": "tryambakam-noesis/brand-docs-final",
    "status": "awaiting-ingestion"
  },
  "branding": {
    "path": "tryambakam-noesis/branding",
    "status": "awaiting-ingestion"
  },
  "bv-pip": {
    "path": "tryambakam-noesis/bv-pip",
    "status": "awaiting-ingestion"
  },
  "content-engine": {
    "path": "tryambakam-noesis/content-engine",
    "status": "awaiting-ingestion"
  },
  "cosmo-align-workspace": {
    "path": "tryambakam-noesis/cosmo-align-workspace",
    "status": "awaiting-ingestion"
  },
  "dakm-philosophy": {
    "path": "tryambakam-noesis/dakm-philosophy",
    "status": "awaiting-ingestion"
  },
  "noesismirror-web-falseearth": {
    "path": "tryambakam-noesis/noesismirror-web-falseearth",
    "status": "awaiting-ingestion"
  },
  "paperclip-tn": {
    "path": "tryambakam-noesis/paperclip-tn",
    "status": "awaiting-ingestion"
  },
  "phase-ion": {
    "path": "tryambakam-noesis/phase-ion",
    "status": "awaiting-ingestion"
  },
  "polyhymnia": {
    "path": "tryambakam-noesis/polyhymnia",
    "status": "empty-hold"
  },
  "selemene-engine": {
    "path": "tryambakam-noesis/selemene-engine",
    "status": "awaiting-ingestion"
  },
  "selemene-gw": {
    "path": "tryambakam-noesis/selemene-gw",
    "status": "awaiting-ingestion"
  },
  "serpentine-raising": {
    "path": "tryambakam-noesis/serpentine-raising",
    "status": "awaiting-ingestion"
  },
  "somatic-canticles-book": {
    "path": "tryambakam-noesis/somatic-canticles-book",
    "status": "awaiting-ingestion"
  },
  "somatic-canticles-mobile-app": {
    "path": "tryambakam-noesis/somatic-canticles-mobile-app",
    "status": "awaiting-ingestion"
  },
  "somatic-canticles-webapp": {
    "path": "tryambakam-noesis/somatic-canticles-webapp",
    "status": "awaiting-ingestion"
  },
  "synchronocities-blog": {
    "path": "tryambakam-noesis/synchronocities-blog",
    "status": "awaiting-ingestion"
  },
  "tpothp": {
    "path": "tryambakam-noesis/tpothp",
    "status": "awaiting-ingestion"
  },
  "tryambakam-space": {
    "path": "tryambakam-noesis/tryambakam-space",
    "status": "awaiting-ingestion"
  },
  "twc-shell": {
    "path": "tryambakam-noesis/twc-shell",
    "status": "awaiting-ingestion"
  },
  "urania-137": {
    "path": "tryambakam-noesis/urania-137",
    "status": "awaiting-ingestion"
  },
  "watchthisokay-stremio": {
    "path": "tryambakam-noesis/watchthisokay-stremio",
    "status": "awaiting-ingestion"
  },
  "witness-agents": {
    "path": "tryambakam-noesis/witness-agents",
    "status": "awaiting-ingestion"
  },
  "witness0s-webshore": {
    "path": "tryambakam-noesis/witness0s-webshore",
    "status": "awaiting-ingestion"
  }
} as const;
