// Generated by scripts/generate-portfolio-root-map.mjs. Do not edit.
// The proposal census can advance independently; admin actions stay bound to the reviewed execution pin.
export const PORTFOLIO_ROOT_MAP_DIGEST = "4efebf84f5eea45b134aca43a4a60eaebdb06981088fc26205eb6d2abf797ec2" as const;
export const REVIEWED_PORTFOLIO_ROOT_MAP_DIGEST = "e2abef8080c6ababab7a41e1803fa1eccc08b58a4dbf7876e586df78493bf351" as const;
export const PORTFOLIO_ROOTS = [
  {
    "portfolioId": "thoughtseed",
    "label": "Thoughtseed",
    "itemLabel": "WorkObject",
    "folderCount": 71,
    "infrastructure": [
      "_physical-relocation-archive-2026-08-08",
      "openfang",
      "scroll-world",
      "thoughtseed-labs",
      "website",
      ".codex-data",
      ".grok-worktrees",
      ".superpowers",
      ".superset-worktrees",
      "omniroute-governed",
      "temperance_engine-phase-01",
      ".cambium-recovery-20261004",
      ".worktrees",
      "_archive",
      "cambium-atlas-app-wiring-20261007",
      "cambium-curious-release-20261008",
      "cambium-curious-scene-visuals-20261007",
      "cambium-stage3-readiness",
      "cambium-system-atlas-20261007",
      "cambium-website-intake-20260924",
      "hermes-cron-repair-20261007",
      "hermes-cron-repair-20261008",
      "hermes-growth-portfolio-review-20261001",
      "hermes-stage3-readiness",
      "hermes-vault-reconciliation-20261007",
      "mcp-obsidian-slice-b-20261001-artifacts",
      "thoughtseed-labs-axtech-brand-map",
      "thoughtseed-labs-docs-cleanup",
      "thoughtseed-labs-growth-atlas-20261007",
      "thoughtseed-labs-hosted-router",
      "tirak-recovery-2026-09-09"
    ],
    "folders": [
      {
        "folder": "Airdronauts",
        "proposedKind": "client-branch",
        "accountId": "airdronauts-productions",
        "workIds": [
          "branch:airdronauts-panorama-viewer-delivery"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "agentfount",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:agentfount"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "archived-thoughtseedlabs-website",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:company-website"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "ashwinsheth-group",
        "proposedKind": "client-branch",
        "accountId": "ashwin-sheth-group",
        "workIds": [
          "branch:ashwinsheth-marina-one-mumbai",
          "branch:ashwinsheth-marina-one-bangalore"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "autosocial",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "reference-unresolved",
        "referenceKind": "external-adapter",
        "sourceRefs": [
          "local:autosocial/.git/config",
          "repo:Katzca/AutoSocial"
        ]
      },
      {
        "folder": "brand-genesis",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "brandmint",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "brandmint-oracle-aleph",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "bwssb",
        "proposedKind": "client-branch",
        "accountId": "spaceblanket-ai",
        "workIds": [
          "branch:bwssb"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "cambium",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:cambium",
          "program:cambium-operating-fabric"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "cambium-showcase-ui-rebuild",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:cambium"
        ],
        "status": "mapping-proposal",
        "displayName": "Cambium Website",
        "sourceRefs": [
          "local:cambium-showcase-ui-rebuild/package.json#name",
          "local:.cambium-recovery-20261004/cleanup-receipt.json#activeCheckout"
        ]
      },
      {
        "folder": "codigo",
        "proposedKind": "client-branch",
        "accountId": "codigo-olimpo",
        "workIds": [
          "branch:codigo-olimpo",
          "branch:codigo-olimpo-creator-platform"
        ],
        "status": "mapping-proposal",
        "displayName": "Codigo",
        "nestedRepositories": [
          {
            "relativePath": "research/Decodik",
            "displayName": "Decodik",
            "workIds": [
              "branch:codigo-olimpo",
              "branch:codigo-olimpo-creator-platform"
            ]
          }
        ]
      },
      {
        "folder": "coproperty",
        "proposedKind": "client-branch",
        "accountId": "co-property",
        "workIds": [
          "branch:co-property",
          "sapling:nimbus-gate",
          "sapling:wanderfruit"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "earthy-munchy",
        "proposedKind": "client-branch",
        "accountId": "yamuna-foods",
        "workIds": [
          "branch:earthy-munchy"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "factor",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "identity-unresolved",
        "referenceKind": "identity-intake",
        "sourceRefs": [
          "local:factor/README.md",
          "repo:Sheshiyer/factor"
        ]
      },
      {
        "folder": "fieldwork",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "identity-unresolved",
        "referenceKind": "identity-intake",
        "sourceRefs": [
          "local:fieldwork/README.md",
          "repo:Sheshiyer/field-report"
        ]
      },
      {
        "folder": "fitcheck-landing",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:fitcheck"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "fitcheck-wiki",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:fitcheck"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "fmrl",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:fmrl"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "fmrl-reactnative",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:fmrl"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "gram-cli",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:operator-utilities"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "hdilint-backend-aleph",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:hdilint"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "hermes-aws-ts",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:temperance-hermes"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "heyzack",
        "proposedKind": "client-branch",
        "accountId": "heyzack",
        "workIds": [
          "branch:heyzack",
          "branch:heyzack-zackai",
          "branch:heyzack-crm",
          "branch:heyzack-estimate",
          "branch:heyzack-partner-portal",
          "branch:heyzack-customer-portal",
          "branch:heyzack-panel-app",
          "branch:heyzack-landing",
          "branch:heyzack-tooling",
          "branch:heyzack-proposal",
          "branch:heyzack-veloren-cee-ai"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "hostscale",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:hostscale"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "insightreality",
        "proposedKind": "client-branch",
        "accountId": "insight-realtors-legal-advisors",
        "workIds": [
          "branch:insight-realtors-legal-advisors"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "iverif",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:iverif"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "kacima",
        "proposedKind": "client-branch",
        "accountId": "kacima",
        "workIds": [
          "branch:kacima"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "klear-karma",
        "proposedKind": "client-branch",
        "accountId": "klear-karma",
        "workIds": [
          "branch:klear-karma"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "kristudios",
        "proposedKind": "client-branch",
        "accountId": "kristudios",
        "workIds": [
          "branch:kristudios"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "landingpage-ts-2026",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:company-website"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "mcp-obsidian-slice-b-20261001",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "reference-unresolved",
        "referenceKind": "external-adapter",
        "sourceRefs": [
          "local:mcp-obsidian-slice-b-20261001/.git/config",
          "repo:fazer-ai/mcp-obsidian"
        ]
      },
      {
        "folder": "meristem",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal",
        "ownership": "thoughtseed",
        "relationship": "modular-organ-of",
        "relatedWorkId": "sapling:cambium"
      },
      {
        "folder": "monthlymealprep",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:rasa"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "moodboard-ai-agent",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "identity-unresolved",
        "referenceKind": "identity-intake",
        "sourceRefs": [
          "local:moodboard-ai-agent/.git/config",
          "repo:Sheshiyer/moodboard-ai-agent"
        ]
      },
      {
        "folder": "motionsites-export",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "motionsites-skills",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system",
          "program:skill-clusters"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "newsense",
        "proposedKind": "client-branch",
        "accountId": "newsense",
        "workIds": [
          "branch:newsense"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "panaroma-webapp",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [
          "sapling:vantyx",
          "branch:airdronauts-panorama-viewer-delivery"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "parkarea",
        "proposedKind": "client-branch",
        "accountId": "parkarea",
        "workIds": [
          "branch:parkarea"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "plexus-ts",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:plexus"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "plugins",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "mapping-proposal"
      },
      {
        "folder": "professional-headshot-suite",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:explee-capabilities",
          "program:skill-clusters"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "raycast-extensions",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:operator-utilities"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "readme-skill",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:explee-capabilities",
          "program:operator-utilities",
          "program:skill-clusters"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "reddit-cli",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:operator-utilities"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "safvr",
        "proposedKind": "client-branch",
        "accountId": "safvr",
        "workIds": [
          "branch:safvr-landing-page"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "sandboxlife",
        "proposedKind": "client-branch",
        "accountId": "valore-ventures",
        "workIds": [
          "branch:sandboxlife"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "session-atlas",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:session-atlas"
        ],
        "status": "mapping-proposal",
        "displayName": "Session Atlas",
        "ownership": "thoughtseed",
        "relationship": "modular-organ-of",
        "relatedWorkId": "sapling:cambium",
        "identityStatus": "reviewed-local-node"
      },
      {
        "folder": "skill-clusters",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:skill-clusters"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "skills",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:explee-capabilities",
          "program:engineering-orchestration",
          "program:skill-clusters"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "skills-india-govt",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "identity-unresolved",
        "referenceKind": "identity-intake",
        "sourceRefs": [
          "local:skills-india-govt/plugin.json#name",
          "local:skills-india-govt/README.md"
        ]
      },
      {
        "folder": "snow-gloves-ops",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:snow-gloves-os"
        ],
        "status": "mapping-proposal",
        "referenceKind": "platform-companion",
        "sourceRefs": [
          "local:snow-gloves-ops/README.md",
          "repo:Sheshiyer/snow-gloves-os"
        ]
      },
      {
        "folder": "snow-gloves-os",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:snow-gloves-os"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "snow-gloves-wiki",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:snow-gloves-os"
        ],
        "status": "mapping-proposal",
        "referenceKind": "platform-companion",
        "sourceRefs": [
          "local:snow-gloves-wiki/index.md",
          "repo:Sheshiyer/snow-gloves-wiki"
        ]
      },
      {
        "folder": "synchronized-universe-blog",
        "proposedKind": "client-branch",
        "accountId": "harshita",
        "workIds": [
          "branch:harsh-truths"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "team-forge-ts",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:teamforge-control-plane"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "temperance-engine-landing-page",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:temperance-hermes"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "temperance_engine",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:temperance-hermes"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "thai-seconds-marketplace",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "unmapped",
        "displayName": "Saanmai"
      },
      {
        "folder": "thoughtseed-brand-atlas",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:thoughtseed-brand-atlas",
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "thoughtseed-hermes",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:temperance-hermes"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "thoughtseed-organ-console",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:thoughtseed-organ-console"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "thoughtseedlabs-website",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:company-website"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "thoughtseedos-website",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:company-website"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "tirak",
        "proposedKind": "client-branch",
        "accountId": "tirak",
        "workIds": [
          "branch:tirak"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "valmark",
        "proposedKind": "client-branch",
        "accountId": "valmark",
        "workIds": [
          "branch:valmark"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "vibrasonix",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:vibrasonix"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "virtualtryon-3d",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "empty-hold"
      },
      {
        "folder": "whspr",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:whspr"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "wtfmedia",
        "proposedKind": "client-branch",
        "accountId": "wtf-podcast",
        "workIds": [
          "branch:wtfmedia"
        ],
        "status": "mapping-proposal"
      }
    ],
    "missingClientAccounts": [
      "axdis-group",
      "brightme",
      "dorix",
      "instal",
      "mathis",
      "pongotrasteros",
      "symphonics",
      "thaleos",
      "wattconnect",
      "wegrid"
    ],
    "infrastructureWorkMappings": [
      {
        "folder": "thoughtseed-labs",
        "workIds": [
          "program:thoughtseed-vault"
        ]
      }
    ],
    "infrastructureEvidence": [
      {
        "folder": ".cambium-recovery-20261004",
        "kind": "retained-artifact",
        "sourceRefs": [
          "local:.cambium-recovery-20261004/README.md",
          "local:.cambium-recovery-20261004/cleanup-receipt.json#recoveryBundleVerified"
        ]
      },
      {
        "folder": ".worktrees",
        "kind": "retained-artifact",
        "sourceRefs": [
          "local:.worktrees/plexus-experience-design-20260912/.git",
          "local:.worktrees/teamforge-repository-projection-20260912/.git/config"
        ]
      },
      {
        "folder": "_archive",
        "kind": "retained-artifact",
        "sourceRefs": [
          "local:_archive/snow-gloves-os-modular-2026-10-02/.git/config"
        ]
      },
      {
        "folder": "cambium-atlas-app-wiring-20261007",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:cambium-atlas-app-wiring-20261007/.git",
          "local:cambium/.git/worktrees/cambium-atlas-app-wiring-20261007/gitdir"
        ]
      },
      {
        "folder": "cambium-curious-release-20261008",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:cambium-curious-release-20261008/.git",
          "local:cambium/.git/worktrees/cambium-curious-release-20261008/gitdir"
        ]
      },
      {
        "folder": "cambium-curious-scene-visuals-20261007",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:cambium-curious-scene-visuals-20261007/.git",
          "local:cambium/.git/worktrees/cambium-curious-scene-visuals-20261007/gitdir"
        ]
      },
      {
        "folder": "cambium-stage3-readiness",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:cambium-stage3-readiness/.git",
          "local:cambium/.git/worktrees/cambium-stage3-readiness/gitdir"
        ]
      },
      {
        "folder": "cambium-system-atlas-20261007",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:cambium-system-atlas-20261007/.git",
          "local:cambium/.git/worktrees/cambium-system-atlas-20261007/gitdir"
        ]
      },
      {
        "folder": "cambium-website-intake-20260924",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:cambium-website-intake-20260924/.git",
          "local:cambium/.git/worktrees/cambium-website-intake-20260924/gitdir"
        ]
      },
      {
        "folder": "hermes-cron-repair-20261007",
        "kind": "retained-artifact",
        "sourceRefs": [
          "local:hermes-cron-repair-20261007/installation.json#targets"
        ]
      },
      {
        "folder": "hermes-cron-repair-20261008",
        "kind": "retained-artifact",
        "sourceRefs": [
          "local:hermes-cron-repair-20261008/MODULARITY-REVIEW.md"
        ]
      },
      {
        "folder": "hermes-growth-portfolio-review-20261001",
        "kind": "retained-artifact",
        "sourceRefs": [
          "local:hermes-growth-portfolio-review-20261001/canonical-model-source-bindings.json"
        ]
      },
      {
        "folder": "hermes-stage3-readiness",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:hermes-stage3-readiness/.git",
          "local:hermes-aws-ts/.git/worktrees/hermes-stage3-readiness/gitdir"
        ]
      },
      {
        "folder": "hermes-vault-reconciliation-20261007",
        "kind": "retained-artifact",
        "sourceRefs": [
          "local:hermes-vault-reconciliation-20261007/receipt.json#scope"
        ]
      },
      {
        "folder": "mcp-obsidian-slice-b-20261001-artifacts",
        "kind": "retained-artifact",
        "sourceRefs": [
          "local:mcp-obsidian-slice-b-20261001-artifacts/candidate-receipt.json#source"
        ]
      },
      {
        "folder": "thoughtseed-labs-axtech-brand-map",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:thoughtseed-labs-axtech-brand-map/.git",
          "local:thoughtseed-labs/.git/worktrees/thoughtseed-labs-axtech-brand-map/gitdir"
        ]
      },
      {
        "folder": "thoughtseed-labs-docs-cleanup",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:thoughtseed-labs-docs-cleanup/.git",
          "local:thoughtseed-labs/.git/worktrees/thoughtseed-labs-docs-cleanup/gitdir"
        ]
      },
      {
        "folder": "thoughtseed-labs-growth-atlas-20261007",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:thoughtseed-labs-growth-atlas-20261007/.git",
          "local:thoughtseed-labs/.git/worktrees/thoughtseed-labs-growth-atlas-20261007/gitdir"
        ]
      },
      {
        "folder": "thoughtseed-labs-hosted-router",
        "kind": "linked-worktree",
        "sourceRefs": [
          "local:thoughtseed-labs-hosted-router/.git",
          "local:thoughtseed-labs/.git/worktrees/thoughtseed-labs-hosted-router/gitdir"
        ]
      },
      {
        "folder": "tirak-recovery-2026-09-09",
        "kind": "retained-artifact",
        "sourceRefs": [
          "local:tirak-recovery-2026-09-09/P0-PROVENANCE-DISPOSITION.md"
        ]
      }
    ],
    "historicalFolders": [
      {
        "folder": "cambium-telegram-showcase",
        "disposition": "replaced-checkout",
        "currentFolder": "cambium-showcase-ui-rebuild",
        "sourceRefs": [
          "local:.cambium-recovery-20261004/cleanup-receipt.json#activeCheckout",
          "local:cambium-showcase-ui-rebuild/package.json#name"
        ]
      },
      {
        "folder": "cambium-website-semantics",
        "disposition": "retired-worktree",
        "currentFolder": "cambium-showcase-ui-rebuild",
        "sourceRefs": [
          "history:.planning/quick/260907-5gp-classify-the-cambium-website-semantics-l/260907-5gp-SUMMARY.md",
          "local:.cambium-recovery-20261004/README.md"
        ]
      }
    ],
    "censusObservedAt": "2026-10-08T17:56:44Z"
  },
  {
    "portfolioId": "tryambakam-noesis",
    "label": "Tryambakam · Noesis",
    "itemLabel": "Project",
    "folderCount": 35,
    "folders": [
      {
        "folder": "10869-space-v1",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:10869-space"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "10869x77",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:tryambakam"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "723",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "aleph1319xwebsite",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "aletheos-morphic-nexus",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "antahkarana",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:selemene"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "astrolens",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "astrolens-website",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "brand-docs-final",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "branding",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "bv-pip",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "content-engine",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "cosmo-align-workspace",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "dakm-philosophy",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "FMRL-reactnative",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:fmrl"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "noesis-raycast",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:selemene"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "noesismirror-web",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:tryambakam"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "noesismirror-web-falseearth",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "paperclip-tn",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "phase-ion",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "polyhymnia",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "empty-hold"
      },
      {
        "folder": "sankalpa",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:sankalpa"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "Selemene-engine",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:selemene"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "somatic-canticles-book",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "somatic-canticles-mobile-app",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "branch:somatic-canticles"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "somatic-canticles-webapp",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "somaticcanticles-aleph",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "branch:somatic-canticles"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "spatial-anubis-noesis",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:tryambakam"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "synchronocities-blog",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "program:synchronocities-blog"
        ],
        "status": "mapping-proposal",
        "displayName": "Synchronocities",
        "ownership": "partner",
        "relationship": "personal-affiliated",
        "identityStatus": "reviewed-local-node"
      },
      {
        "folder": "tpothp",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "tryambakam-space",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:tryambakam"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "urania-137",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:selemene"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "watchthisokay-stremio",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "witness-agents",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [
          "sapling:selemene"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "witness0s-webshore",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      }
    ],
    "infrastructure": [
      "_portfolio-audit",
      "antahkarana-recovery-20260831-pzm8eM"
    ],
    "archiveContainer": "_archive",
    "archivedProjects": [
      "noesismirror-web",
      "spatial-anubis-noesis",
      "witness-agents-intro-web"
    ]
  }
] as const;
