// Fixture envelopes for the Telegram mini app visual contract.
// These are not demo progress states; they are regression probes for the
// "no fake progress" rule used by the worker tests.

import { CAMBIUM_LANES, CAMBIUM_SENSES, CAMBIUM_WAKE_STEPS } from '../../../shared/cambium-visual-contract.ts';

const zeroLaneCounts = Object.fromEntries(CAMBIUM_LANES.map((lane) => [lane.id, 0]));
const refreshLifetime = {
  scope: 'until-next-refresh',
  staleAfterMinutes: 360,
  detail: 'expires when the next quest envelope is pushed or the envelope becomes stale',
};
const deterministicFreshDerivedAt = '2026-06-22T09:00:00.000Z';
const deterministicFreshProofClock = '2026-06-22T10:00:00.000Z';
const missingNpcHistory = {
  source: 'missing',
  total: 0,
  contradictions: 0,
  rows: [],
};
const missingNpcAdvice = (target: string) => ({
  status: 'blocked',
  label: 'NO ADVICE',
  detail: 'no durable NPC advice event served',
  proof: 'no durable NPC events served',
  action: { kind: 'collect-evidence', label: 'Record NPC evidence', target },
});

const locked = (arc: string, id: string, title: string, evidence: string) => ({
  arc,
  id,
  title,
  status: 'locked',
  evidence,
});

export const NO_FAKE_PROGRESS_VISUAL_FIXTURE = {
  schema: 1,
  derivedAt: '2026-01-01T00:00:00.000Z',
  source: 'visual-fixture:no-fake-progress',
  tenant: 'cambium',
  beats: [],
  openItems: [],
  commands: null,
  wake: {
    source: 'visual-fixture:no-fake-progress',
    steps: CAMBIUM_WAKE_STEPS.map((step) => ({
      id: step.id,
      status: 'missing',
      detail: step.missing,
      source: 'missing',
      proof: `${step.id}: ${step.missing}`,
      evidence: [],
      gap: step.missing,
      history: {
        source: 'missing',
        total: 0,
        status: 'none',
        proof: 'no operator wake events served',
        rows: [],
      },
    })),
  },
  lanes: {
    source: 'missing',
    total: 0,
    dominant: null,
    counts: zeroLaneCounts,
    gap: 'lane telemetry missing from world.log',
  },
  senses: {
    source: 'quest-ledger-envelope@v1',
    status: 'ready',
    rows: [
      {
        id: 'signal',
        title: CAMBIUM_SENSES.find((sense) => sense.id === 'signal')!.title,
        on: true,
        detail: 'I · The Calling',
        proof: 'I · The Calling: first session unplayed',
        source: 'quest-ledger',
        evidence: [{ label: 'I · The Calling', status: 'active', detail: 'first session unplayed' }],
      },
      {
        id: 'memory',
        title: CAMBIUM_SENSES.find((sense) => sense.id === 'memory')!.title,
        on: false,
        detail: 'no cortex rows',
        proof: 'no tenant cortex memory or open cortex quest rows served',
        source: 'missing',
        evidence: [],
        gap: 'memory sense has no served cortex evidence',
      },
      {
        id: 'risk',
        title: CAMBIUM_SENSES.find((sense) => sense.id === 'risk')!.title,
        on: true,
        detail: '16 quest risk traces · 0 gate risks',
        proof: 'II · First Mint: artifacts pending: seed, positioning, cta unclaimed · VI · Memory: cortex unreachable · XV · The Launch: deploy events missing',
        source: 'quest-ledger',
        evidence: [
          { label: 'II · First Mint', status: 'locked', detail: 'artifacts pending: seed, positioning, cta unclaimed' },
          { label: 'VI · Memory', status: 'locked', detail: 'cortex unreachable' },
          { label: 'XV · The Launch', status: 'locked', detail: 'deploy events missing' },
        ],
      },
      {
        id: 'drift',
        title: CAMBIUM_SENSES.find((sense) => sense.id === 'drift')!.title,
        on: true,
        detail: 'ledger stale beyond 360m',
        proof: 'derivedAt 2026-01-01T00:00:00.000Z',
        source: 'freshness',
        evidence: [{ label: 'derivedAt', status: 'stale', detail: '2026-01-01T00:00:00.000Z' }],
        gap: 'ledger older than 360 minutes',
      },
    ],
  },
  insights: {
    source: 'quest-ledger-evidence@v1',
    status: 'ready',
    rows: [
      {
        id: 'active-frontier:the-calling',
        title: 'I · The Calling',
        state: 'wait',
        detail: 'first session unplayed',
        proof: 'first session unplayed',
        source: 'quest-ledger',
        origin: 'active-frontier',
        quest: { arc: 'I', id: 'the-calling', status: 'active' },
        evidence: [{ label: 'I · The Calling', status: 'active', detail: 'first session unplayed' }],
        gap: 'active frontier is not complete yet',
      },
    ],
  },
  stance: {
    source: 'missing',
    status: 'insufficient',
    scope: 'tenant-world-log-only',
    sampleSize: 0,
    minimum: 6,
    window: 24,
    dominant: null,
    label: null,
    confidence: 0,
    ratios: zeroLaneCounts,
    counts: zeroLaneCounts,
    gap: 'need 6 tenant events; found 0',
  },
  skills: {
    source: 'missing',
    total: 0,
    rows: [],
    gap: 'skill registry missing',
  },
  policy: {
    source: 'operator-policy',
    status: 'blocked',
    action: null,
    title: 'POLICY GAP',
    detail: 'recommendation policy blocked',
    blockers: [
      'need 6 tenant events; found 0',
      'skill registry missing',
    ],
    cautions: [],
    requiredSignals: ['active quest frontier', 'tenant stance sample', 'skill registry tier'],
    rulesVersion: 'operator-policy@v1.4',
    gap: 'need 6 tenant events; found 0',
  },
  npc: {
    source: 'missing',
    relationships: [
      {
        id: 'mira',
        status: 'missing',
        detail: 'npc relationship state not served yet',
        proof: 'no tenant cortex memories served',
        stage: {
          id: 'missing',
          label: 'MISSING',
          detail: 'no tenant-scoped Mira/ICP evidence served',
          confidence: 0,
        },
        events: [],
        history: missingNpcHistory,
        advice: missingNpcAdvice('quine write quests npc-event mira'),
        sampleSize: 0,
        scope: 'tenant-cortex-only',
      },
      {
        id: 'founder-npc',
        status: 'missing',
        detail: 'founder memory not served yet',
        proof: 'no inherited founder arcs served',
        stage: {
          id: 'missing',
          label: 'MISSING',
          detail: 'no inherited founder arc memory served',
          confidence: 0,
        },
        events: [],
        history: missingNpcHistory,
        advice: missingNpcAdvice('quine write quests npc-event founder-npc'),
        sampleSize: 0,
        scope: 'founder-arcs',
      },
    ],
  },
  social: {
    source: 'coordination-evidence@v1',
    status: 'gap',
    scope: 'tenant-handoff-only',
    rows: [
      {
        id: 'social-gap',
        title: 'SOCIAL GAP',
        state: 'gap',
        detail: 'no tenant-scoped bridge or handoff evidence served',
        proof: 'Paperclip open items, founder gate, and client handoff signals are absent',
        source: 'missing',
        scope: 'tenant-handoff-only',
        evidence: [],
        gap: 'coordination evidence missing',
      },
    ],
    gap: 'no tenant-scoped bridge or handoff evidence served',
  },
  decisionContext: {
    source: 'decision-context@v1',
    status: 'ready',
    served: 0,
    gaps: 6,
    rows: [
      {
        id: 'founder-preference',
        title: 'FOUNDER PREFERENCE',
        state: 'gap',
        detail: 'founder preference signal not served',
        proof: 'no founder preference row exists in the current visual envelope',
        source: 'missing',
        scope: 'tenant-only',
        evidence: [],
        gap: 'founder preference missing',
      },
      {
        id: 'owner-load',
        title: 'OWNER LOAD',
        state: 'gap',
        detail: 'no owner load signal served',
        proof: 'no Paperclip open items with owner fields were served',
        source: 'missing',
        scope: 'tenant-only',
        evidence: [],
        gap: 'owner load missing',
      },
      {
        id: 'economic-risk',
        title: 'ECONOMIC RISK',
        state: 'gap',
        detail: 'economic commitment state not served',
        proof: 'no project evidence object served for brief, contract, deposit, amount, or currency',
        source: 'missing',
        scope: 'project-only',
        evidence: [],
        gap: 'economic risk missing',
      },
      {
        id: 'team-availability',
        title: 'TEAM AVAILABILITY',
        state: 'gap',
        detail: 'team availability signal not served',
        proof: 'Paperclip owners are not availability or capacity signals',
        source: 'missing',
        scope: 'tenant-only',
        evidence: [],
        gap: 'team availability missing',
      },
      {
        id: 'member-revocation',
        title: 'MEMBER REVOCATION',
        state: 'gap',
        detail: 'member revocation state not served',
        proof: 'bridge/member token revocation state is not present in the visual envelope',
        source: 'missing',
        scope: 'tenant-only',
        evidence: [],
        gap: 'member revocation missing',
      },
      {
        id: 'cross-tenant-urgency',
        title: 'CROSS-TENANT URGENCY',
        state: 'gap',
        detail: 'cross-tenant urgency signal not served',
        proof: 'no tenant registry or urgency score served',
        source: 'missing',
        scope: 'cross-tenant',
        evidence: [],
        gap: 'cross-tenant urgency missing',
      },
    ],
  },
  liveProof: {
    source: 'tg-live-proof-readiness@v1',
    status: 'blocked',
    generatedAt: '2026-06-22T00:00:00.000Z',
    workerUrl: 'https://curious.thoughtseed.space',
    summary: {
      ready: 7,
      blocked: 3,
      total: 10,
      liveProofReady: false,
    },
    invariant: 'Capture commands create redacted receipts; they are proof only after their artifacts validate ready.',
    rows: [
      {
        id: 'device-webview-proof',
        title: 'DEVICE WEBVIEW PROOF',
        state: 'blocked',
        detail: '3/4 prerequisites blocked',
        proof: 'docs/plans/assets/tg-miniapp-live-proof/telegram-webview.json; capture plan is guidance, not proof',
        source: 'tg-live-proof-capture-plan',
        command: 'node workers/quests/src/live-proof-readiness.mjs --capture-device-proof --screenshot docs/plans/assets/tg-miniapp-live-proof/<founder-device>.png --platform <ios|android|desktop> --webview-url <current Telegram WebView URL> --safe-area <notes> --write',
        writes: 'docs/plans/assets/tg-miniapp-live-proof/telegram-webview.json',
        prerequisites: [
          { label: 'fresh-telegram-init-data', status: 'blocked', detail: 'capture fresh TELEGRAM_INIT_DATA or TG_INIT_DATA from a founder Telegram WebView' },
          { label: 'screenshot-under-proof-dir', status: 'blocked', detail: 'founder-device screenshot path is required' },
          { label: 'device-platform', status: 'blocked', detail: 'device platform is required' },
          { label: 'webview-url', status: 'ready', detail: 'WebView URL is supplied' },
        ],
        privacy: [
          'raw initData comes only from env',
          'artifact stores user/initData/screenshot hashes only',
          'WebView query and hash are omitted',
        ],
      },
      {
        id: 'worker-list-proof',
        title: 'WORKER LIST PROOF',
        state: 'blocked',
        detail: 'worker-network-probe.json is stale or not trusted by the current readiness packet',
        proof: 'current readiness blocks worker-network-probe until a fresh cambium.worker-network-probe.v1 receipt validates ready',
        source: 'tg-live-proof-capture-plan',
        command: 'node workers/quests/src/live-proof-readiness.mjs --capture-worker-probe --allow-network --write',
        writes: 'docs/plans/assets/tg-miniapp-live-proof/worker-network-probe.json',
        prerequisites: [
          { label: 'worker-token', status: 'ready', detail: 'QUESTS_PUSH_TOKEN is available without printing it' },
          { label: 'allow-network', status: 'blocked', detail: '--allow-network is required for recapture' },
        ],
        privacy: [
          'Worker credential is used only as an authorization header',
          'artifact stores status, response shape, counts, and body digest only',
        ],
      },
      {
        id: 'signed-action-smoke',
        title: 'SIGNED ACTION SMOKE',
        state: 'blocked',
        detail: '12/14 prerequisites blocked',
        proof: 'docs/plans/assets/tg-miniapp-live-proof/signed-action-smoke.json; capture plan is guidance, not proof',
        source: 'tg-live-proof-capture-plan',
        command: 'node workers/quests/src/live-proof-readiness.mjs --capture-signed-smoke --allow-network --allow-mutation --action-kind <kind> --action-subject <subject> --action-idempotency-key <key> --operator-command "<consumer command>" --operator-audit <audit-file> --operator-checked <n> --operator-consumed <n> --operator-rejected <n> --miniapp-envelope <refreshed-envelope-file> --visible-marker <visible-card-marker> --write',
        writes: 'docs/plans/assets/tg-miniapp-live-proof/signed-action-smoke.json',
        prerequisites: [
          { label: 'fresh-telegram-init-data', status: 'blocked', detail: 'capture fresh TELEGRAM_INIT_DATA or TG_INIT_DATA from a founder Telegram WebView' },
          { label: 'worker-token', status: 'ready', detail: 'QUESTS_PUSH_TOKEN is available without printing it' },
          { label: 'allow-network', status: 'blocked', detail: '--allow-network is required for this capture' },
          { label: 'allow-mutation', status: 'blocked', detail: '--allow-mutation is required for this capture' },
          { label: 'miniapp-envelope', status: 'blocked', detail: 'mini app envelope path is required' },
          { label: 'visible-marker', status: 'blocked', detail: 'visible marker is required' },
        ],
        privacy: [
          'raw initData is sent only in the Telegram submit body',
          'proof tool does not consume the queue',
          'artifact stores hashes, counts, status codes, and digests only',
        ],
      },
    ],
    gap: 'live Telegram WebView and Worker proof are not complete yet',
  },
  sideQuests: {
    source: 'pure-trigger-predicates',
    status: 'ready',
    rows: [
      {
        id: 'wake-proof',
        title: 'WAKE PROOF',
        status: 'triggered',
        trigger: 'wake.steps.missing',
        detail: '6 wake steps awaiting signal',
        proof: 'ingest: missing source · route: missing active route · act: no available quest rows · viability: awaiting signal · learn: awaiting signal · persist: missing derivedAt',
        origin: 'visual-fixture:no-fake-progress',
        owner: 'operator',
        action: { kind: 'refresh', label: 'Refresh quest evidence', target: 'quine write quests push' },
        lifetime: refreshLifetime,
        completion: { kind: 'proof-arrives', proof: 'all wake steps referenced by this row become proved or explicitly absent' },
      },
      {
        id: 'stance-sample',
        title: 'STANCE SAMPLE',
        status: 'triggered',
        trigger: 'stance.insufficient',
        detail: 'need 6 tenant events; found 0',
        proof: '0/6 tenant lane events',
        origin: 'missing',
        owner: 'operator',
        action: { kind: 'collect-evidence', label: 'Record tenant lane events', target: 'tenant world.log' },
        lifetime: { scope: 'until-evidence-arrives', staleAfterMinutes: 360, detail: 'remains open until tenant lane sample reaches the minimum' },
        completion: { kind: 'proof-arrives', proof: 'tenant stance sample reaches 6 events' },
      },
      {
        id: 'skill-registry',
        title: 'SKILL REGISTRY',
        status: 'triggered',
        trigger: 'skills.missing',
        detail: 'skill registry missing',
        proof: '0/0 served skill telemetry rows',
        origin: 'missing',
        owner: 'operator',
        action: { kind: 'refresh', label: 'Refresh skill telemetry', target: '.operator/<tenant>.skills.json' },
        lifetime: refreshLifetime,
        completion: { kind: 'proof-arrives', proof: 'skill registry serves at least one telemetry row' },
      },
      {
        id: 'policy-unblock',
        title: 'POLICY UNBLOCK',
        status: 'triggered',
        trigger: 'policy.blocked',
        detail: 'need 6 tenant events; found 0',
        proof: 'need 6 tenant events; found 0 · skill registry missing',
        origin: 'operator-policy',
        owner: 'system',
        action: { kind: 'inspect', label: 'Inspect policy blockers', target: 'operator-policy@v1.4' },
        lifetime: refreshLifetime,
        completion: { kind: 'policy-ready', proof: 'operator policy serves a ready next action or a narrower blocker' },
      },
      {
        id: 'mira-evidence',
        title: 'MIRA EVIDENCE',
        status: 'triggered',
        trigger: 'npc.mira.missing',
        detail: 'npc relationship state not served yet',
        proof: '0 tenant cortex matches',
        origin: 'missing',
        owner: 'operator',
        action: { kind: 'collect-evidence', label: 'Mint tenant cortex memory', target: 'npc.mira' },
        lifetime: { scope: 'until-evidence-arrives', staleAfterMinutes: 1440, detail: 'remains open until tenant cortex evidence mentions Mira or ICP signals' },
        completion: { kind: 'proof-arrives', proof: 'tenant-scoped cortex memory backs Mira relationship evidence' },
      },
    ],
  },
  ledger: {
    completed: 0,
    total: 17,
    current: { arc: 'I', id: 'the-calling', title: 'The Calling' },
    rows: [
      { arc: 'I', id: 'the-calling', title: 'The Calling', status: 'active', evidence: 'first session unplayed' },
      locked('II', 'first-mint', 'First Mint', 'artifacts pending: seed, positioning, cta unclaimed'),
      locked('III', 'taste-resonance', 'Taste & Resonance', 'no meso moves yet'),
      locked('IV', 'the-loop', 'The Loop', 'micro x0, meso x0, macro x0'),
      locked('V', 'viability', 'Viability', 'viability sweep unplayed'),
      locked('VI', 'memory', 'Memory', 'cortex unreachable'),
      locked('VII', 'many-gardens', 'Many Gardens', 'tenant garden evidence missing'),
      locked('VIII', 'living-org', 'Living Org', 'Paperclip org unreachable'),
      locked('IX', 'the-gate', 'The Gate', 'no founder handoff resolved'),
      locked('X', 'the-brief', 'The Brief', 'brief, contract, and deposit missing'),
      locked('XI', 'the-scaffold', 'The Scaffold', 'repo, tenant, and specs missing'),
      locked('XII', 'the-build', 'The Build', 'build commits missing'),
      locked('XIII', 'the-review', 'The Review', 'review events missing'),
      locked('XIV', 'the-ship-gate', 'The Ship Gate', 'gate approvals missing'),
      locked('XV', 'the-launch', 'The Launch', 'deploy events missing'),
      locked('XVI', 'the-handoff', 'The Handoff', 'client sign-off missing'),
      locked('XVII', 'the-garden', 'The Garden', 'lessons and archive missing'),
    ],
  },
} as const;

export const FRESH_ECOSYSTEM_VISUAL_FIXTURE = {
  ...NO_FAKE_PROGRESS_VISUAL_FIXTURE,
  derivedAt: deterministicFreshDerivedAt,
  source: 'visual-fixture:fresh-ecosystem',
  freshness: {
    status: 'fresh',
    staleAfterMinutes: 360,
    detail: 'derived just now',
    proofClock: deterministicFreshProofClock,
    proof: `deterministic derivedAt ${deterministicFreshDerivedAt} is 60 minutes before fixture proof clock ${deterministicFreshProofClock}`,
  },
  commands: {
    status: { agents: 3, issuesOpen: 2, issuesDone: 7, arcs: '3/17', hermes: 'ready' },
    services: [
      { name: 'Hermes Telegram brain', status: 'ready', detail: 'curios.self command bridge reachable' },
      { name: 'Cambium Worker', status: 'ready', detail: 'quest envelope route responding for cambium' },
    ],
    agents: [
      { name: 'Mira', model: 'operator-npc-events@v1' },
      { name: 'Paperclip', model: 'vault-via-paperclip' },
    ],
    work: [
      { id: 'THO-42', status: 'active', title: 'Refresh mini app proof surface', who: 'operator' },
    ],
    handoffs: [
      { id: 'HND-7', status: 'waiting-founder', title: 'Approve fresh viewport capture' },
    ],
  },
  beats: [
    { text: 'Hermes routed a fresh command snapshot into the mini app', lane: 'paperclip', noesis: false },
    { text: 'NOESIS check kept stale screenshots out of readiness', lane: 'noesis', noesis: true },
  ],
  rails: {
    source: 'shared/cambium-visual-contract',
    proof: '5 organs and 7 rails served from shared/cambium-visual-contract.ts',
    rows: CAMBIUM_LANES.map((lane) => ({ id: lane.id, source: 'shared/cambium-visual-contract', proof: `${lane.title} lane is mapped` })),
  },
  sourceProofs: [
    { id: 'commands', source: 'paperclipCommandsData', proof: 'live command sheet rows have source metadata' },
    { id: 'beats', source: 'operator-narrative', proof: 'story beats carry lane and narrative source' },
    { id: 'rails', source: 'shared/cambium-visual-contract', proof: 'rail rows are read-only contract evidence' },
  ],
} as const;

export const STALE_ECOSYSTEM_VISUAL_FIXTURE = {
  ...NO_FAKE_PROGRESS_VISUAL_FIXTURE,
  derivedAt: '2026-01-01T00:00:00.000Z',
  source: 'visual-fixture:stale-ecosystem',
  stale: {
    status: 'stale',
    staleAfterMinutes: 360,
    reasons: [
      'derivedAt is older than six hours',
      'stale data is not live proof',
      'refresh command: quine write quests push --tenant cambium',
    ],
  },
} as const;

export const OFFLINE_ECOSYSTEM_VISUAL_FIXTURE = {
  ...NO_FAKE_PROGRESS_VISUAL_FIXTURE,
  derivedAt: '2026-01-01T00:00:00.000Z',
  source: 'visual-fixture:offline-ecosystem',
  commands: null,
  wake: {
    ...NO_FAKE_PROGRESS_VISUAL_FIXTURE.wake,
    source: 'missing',
    gap: 'wake source offline; commands, live proof, and Paperclip are unavailable',
    steps: NO_FAKE_PROGRESS_VISUAL_FIXTURE.wake.steps.map((step) => ({
      ...step,
      status: 'missing',
      source: 'missing',
      detail: `offline gap: ${step.detail}`,
      proof: 'offline fixture does not serve wake proof',
    })),
  },
  liveProof: {
    source: 'missing',
    status: 'blocked',
    rows: [],
    gap: 'live proof source offline; no Telegram WebView, Worker, or signed smoke receipt served',
  },
  social: {
    source: 'missing',
    status: 'gap',
    scope: 'tenant-handoff-only',
    rows: [
      {
        id: 'paperclip-offline',
        title: 'PAPERCLIP OFFLINE',
        state: 'gap',
        detail: 'Paperclip coordination evidence is unavailable',
        proof: 'offline fixture intentionally omits Paperclip handoff rows',
        source: 'missing',
        scope: 'tenant-handoff-only',
        evidence: [],
      },
    ],
  },
  paperclip: {
    source: 'missing',
    gap: 'Paperclip unavailable in offline ecosystem fixture',
  },
} as const;
