import { SYSTEM_ATLAS } from '../../../../../shared/cambium-system-atlas.ts';
import { SYSTEM_ATLAS_PORTRAITS } from '../../../../../shared/cambium-system-atlas-portraits.ts';

// Scoped styles share the pocket palette; no global reset or motion dependency.
export const SYSTEM_ATLAS_CSS = String.raw`
.atlas{--atlas-bg:var(--bg,#00272B);--atlas-panel:var(--bg2,#012F34);--atlas-ink:var(--ink,#E0FF4F);--atlas-soft:var(--soft,#D6FFF6);--atlas-warn:var(--warn,#FFC7A1);color:var(--atlas-soft);container-type:inline-size;width:100%;min-width:0;margin:8px 0 24px;border:1px solid rgba(214,255,246,.16);border-radius:16px;background:linear-gradient(135deg,rgba(1,47,52,.92),rgba(0,39,43,.94));overflow:hidden;isolation:isolate}
.atlas *{box-sizing:border-box}.atlas button{font:inherit;cursor:pointer;touch-action:manipulation}.atlas button:focus-visible,.atlas summary:focus-visible{outline:2px solid var(--atlas-ink);outline-offset:4px}.atlas button:disabled{cursor:default}
.atlas-heading{padding:24px 24px 16px;display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.atlas-kicker{font:10px/1.5 var(--mono,monospace);letter-spacing:.14em;text-transform:uppercase;color:var(--atlas-ink)}.atlas-heading h3{font-size:clamp(25px,3.5vw,38px);font-weight:600;line-height:1.1;letter-spacing:-.035em;margin:8px 0}.atlas-heading p{font-size:12px;opacity:.76;margin-top:8px}.atlas-stamp{border:1px dashed rgba(214,255,246,.38);border-radius:999px;padding:6px 10px;white-space:nowrap;font:10px/1.4 var(--mono,monospace)}
.atlas-tabs{display:flex;gap:0;border-top:1px solid rgba(214,255,246,.09);border-bottom:1px solid rgba(214,255,246,.16);padding:0 16px}.atlas-tabs button{min-height:48px;padding:0 16px;border:0;border-bottom:2px solid transparent;background:none;color:var(--atlas-soft);font:11px var(--mono,monospace);opacity:.65}.atlas-tabs button[aria-selected=true]{color:var(--atlas-ink);opacity:1;border-bottom-color:var(--atlas-ink)}
.atlas-body{padding:16px}.atlas-layout{display:grid;grid-template-columns:minmax(0,2.25fr) minmax(224px,1fr);gap:16px;align-items:start}.atlas-map{position:relative;height:480px;min-width:0;border:1px solid rgba(214,255,246,.09);border-radius:12px;overflow:hidden;background:repeating-radial-gradient(ellipse at 49% 48%,transparent 0 19px,rgba(214,255,246,.028) 20px 21px,transparent 22px 38px)}
.atlas-map svg.atlas-rails{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.atlas-rails path{fill:none;stroke:rgba(214,255,246,.24);stroke-width:1.1;vector-effect:non-scaling-stroke}.atlas-rails path[data-kind=knowledge]{stroke-dasharray:2 5}.atlas-rails path[data-kind=evidence]{stroke-dasharray:7 4}.atlas-rails path[data-kind=projection]{stroke-dasharray:2 7;stroke:rgba(214,255,246,.42)}.atlas-rails path.is-selected{stroke:var(--atlas-ink);stroke-width:1.8}.atlas-rails text{fill:var(--atlas-soft);font:12px monospace;opacity:.64}.atlas-map-caption{position:absolute;left:20px;top:18px;font:10px/1.5 var(--mono,monospace);letter-spacing:.1em;text-transform:uppercase}.atlas-map-caption.operator{top:63%;color:var(--atlas-soft)}.atlas-map-caption small{display:block;font:10px/1.5 var(--mono,monospace);opacity:.6;letter-spacing:0;text-transform:none;margin-top:4px}
.atlas-node{position:absolute;left:var(--x);top:var(--y);transform:translate(-50%,-50%);width:88px;min-height:88px;border:0;background:none;color:var(--atlas-soft);display:grid;justify-items:center;gap:4px;z-index:1;padding:4px;border-radius:10px}.atlas-node img{width:62px;height:62px;object-fit:contain;border-radius:50%;background:#082d31;border:1px solid rgba(214,255,246,.16);padding:1px}.atlas-node b{font-size:12px;font-weight:600}.atlas-node small{font:9px var(--mono,monospace);opacity:.62}.atlas-node[aria-pressed=true]{color:var(--atlas-ink)}.atlas-node[aria-pressed=true] img{border:2px solid var(--atlas-ink);box-shadow:0 0 0 5px rgba(224,255,79,.09)}.atlas-node:focus-visible{outline-offset:0}
.atlas-detail{border:1px solid rgba(214,255,246,.16);border-radius:12px;background:rgba(0,39,43,.42);overflow:hidden;min-width:0}.atlas-detail-image{width:100%;height:184px;object-fit:contain;background:radial-gradient(ellipse at 50% 60%,rgba(224,255,79,.06),transparent 70%);display:block}.atlas-detail-copy{padding:16px}.atlas-detail h4{font-size:24px;font-weight:600;letter-spacing:-.03em;line-height:1.1;margin:8px 0 10px}.atlas-purpose{font-size:13px;line-height:1.5;opacity:.82}.atlas-io{display:grid;gap:12px;margin:20px 0}.atlas-io-label{font:9px var(--mono,monospace);letter-spacing:.14em;text-transform:uppercase;color:var(--atlas-ink);margin-bottom:6px}.atlas-chips{display:flex;flex-wrap:wrap;gap:6px}.atlas-chips span{padding:5px 8px;border:1px solid rgba(214,255,246,.16);border-radius:4px;font-size:11px;line-height:1.4}.atlas-boundary{border-left:2px solid var(--atlas-warn);padding-left:10px;font-size:11px;line-height:1.5;color:var(--atlas-warn)}.atlas-source{border-top:1px solid rgba(214,255,246,.09);margin-top:16px;padding-top:10px}.atlas-source summary{cursor:pointer;font:10px/1.5 var(--mono,monospace);min-height:44px;display:flex;align-items:center;gap:8px}.atlas-source summary::before{content:'+';color:var(--atlas-ink)}.atlas-source[open] summary::before{content:'−'}.atlas-source code{display:block;font:10px/1.6 var(--mono,monospace);overflow-wrap:anywhere;opacity:.72;margin:6px 0}.atlas-source p{font:10px/1.5 var(--mono,monospace);color:var(--atlas-warn)}
.atlas-legend{display:flex;flex-wrap:wrap;gap:16px;padding:16px 4px 0;font:9px/1.5 var(--mono,monospace);color:var(--atlas-soft);opacity:.78}.atlas-legend span{display:flex;gap:6px;align-items:center}.atlas-legend i{width:22px;border-top:1px solid var(--atlas-soft)}.atlas-legend [data-kind=knowledge] i{border-top-style:dotted}.atlas-legend [data-kind=evidence] i{border-top-style:dashed}.atlas-legend [data-kind=projection] i{border-color:var(--atlas-soft);border-top-style:dotted}.atlas-foot{padding:12px 20px;border-top:1px solid rgba(214,255,246,.09);display:flex;justify-content:space-between;gap:12px;font:9px/1.6 var(--mono,monospace);opacity:.7}
.atlas-paths{display:grid;gap:20px;min-width:0}.atlas-path-block{border:1px solid rgba(214,255,246,.09);border-radius:12px;padding:16px;background:rgba(0,39,43,.3)}.atlas-section-title{font:10px/1.6 var(--mono,monospace);letter-spacing:.08em;color:var(--atlas-ink);margin-bottom:14px}.atlas-path{display:flex;align-items:stretch;gap:16px;min-width:0}.atlas-system{flex:1;min-width:0;position:relative;min-height:80px;background:transparent;border:1px solid rgba(214,255,246,.16);border-radius:8px;padding:12px 8px;color:var(--atlas-soft);text-align:left}.atlas-system b{display:block;font-size:12px}.atlas-system small{display:block;font:9px/1.5 var(--mono,monospace);opacity:.66;margin-top:8px;overflow-wrap:anywhere}.atlas-path.chain .atlas-system:not(:last-child)::after{content:'→';position:absolute;right:-14px;top:30px;color:var(--atlas-ink);font-size:12px}.atlas-system[aria-pressed=true]{border-color:var(--atlas-ink);color:var(--atlas-ink)}.atlas-path-note{margin-top:12px;font:10px/1.6 var(--mono,monospace);opacity:.75}.atlas-link-list{display:grid;gap:8px;margin:16px 0}.atlas-link-item{font-size:11px;line-height:1.5;display:grid;gap:2px;border-top:1px solid rgba(214,255,246,.09);padding-top:8px}.atlas-link-item b{font-weight:500;color:var(--atlas-ink)}.atlas-link-item small{font:9px/1.5 var(--mono,monospace);opacity:.62}
.atlas-growth-header{display:flex;gap:12px;align-items:center;padding:12px 4px 20px}.atlas-growth-header img{width:72px;height:72px;object-fit:contain}.atlas-growth-header h4{font-size:24px;letter-spacing:-.03em}.atlas-growth-header p{font-size:12px;opacity:.75;margin-top:4px}.atlas-desks{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.atlas-desk{background:rgba(0,39,43,.3);color:var(--atlas-soft);border:1px solid rgba(214,255,246,.16);border-radius:10px;min-height:128px;padding:16px;text-align:left}.atlas-desk .atlas-desk-number{font:9px var(--mono,monospace);color:var(--atlas-ink)}.atlas-desk b{display:block;font-size:14px;margin:16px 0 8px}.atlas-desk small{font:10px/1.5 var(--mono,monospace);opacity:.66}.atlas-desk[aria-pressed=true]{border-color:var(--atlas-ink)}.atlas-growth-loop{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));margin-top:20px;gap:1px;background:rgba(214,255,246,.16);border:1px solid rgba(214,255,246,.16);border-radius:8px;overflow:hidden}.atlas-growth-step{padding:14px 10px;background:var(--atlas-bg)}.atlas-growth-step b{display:block;font:11px var(--mono,monospace);color:var(--atlas-ink)}.atlas-growth-step small{display:block;font-size:10px;opacity:.7;line-height:1.5;margin-top:8px}.atlas-growth-step[data-step=approve],.atlas-growth-step[data-step=publish]{border-top:2px solid var(--atlas-warn)}
.atlas-strata{display:grid;gap:10px}.atlas-stratum{padding:24px;border:1px solid rgba(214,255,246,.16);border-radius:12px;position:relative;background:repeating-linear-gradient(-12deg,rgba(214,255,246,.016),rgba(214,255,246,.016) 1px,transparent 1px,transparent 12px)}.atlas-stratum small{font:10px var(--mono,monospace);color:var(--atlas-ink)}.atlas-stratum h4{font-size:24px;letter-spacing:-.025em;margin:12px 0 8px}.atlas-stratum p{font-size:13px;line-height:1.5;opacity:.8}.atlas-stratum code{display:block;margin-top:16px;font:10px var(--mono,monospace);opacity:.65}.atlas-holds{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:20px}.atlas-hold{padding:16px;border:1px dashed rgba(255,199,161,.35);border-radius:8px}.atlas-hold b{font:11px var(--mono,monospace);color:var(--atlas-warn)}.atlas-hold p{font-size:11px;line-height:1.6;opacity:.76;margin-top:8px}.atlas-retired{font:10px/1.8 var(--mono,monospace);opacity:.6;margin:20px 0 0}.atlas-link-action{min-height:44px;margin-top:16px;border:1px solid rgba(214,255,246,.3);border-radius:6px;padding:8px 12px;background:none;color:var(--atlas-soft);font:11px var(--mono,monospace)}
@media(min-width:1200px){.atlas-map{height:540px}.atlas-node{width:100px}.atlas-node img{width:72px;height:72px}.atlas-node b{font-size:13px}}
@media(max-width:700px){.atlas-heading{padding:20px 16px 14px;gap:8px}.atlas-heading h3{font-size:27px}.atlas-stamp{font-size:9px;padding:5px 8px}.atlas-tabs{padding:0 8px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr))}.atlas-tabs button{padding:0 4px;font-size:10px}.atlas-body{padding:12px}.atlas-layout{grid-template-columns:minmax(0,1fr)}.atlas-map{height:auto;background:none;overflow:visible;border:0}.atlas-map svg.atlas-rails{display:none}.atlas-family-group{margin-bottom:16px;min-width:0}.atlas-map-caption{position:static;margin:8px 0 12px;font-size:10px}.atlas-map-caption.operator{position:static}.atlas-family-nodes{display:flex;overflow-x:auto;gap:8px;padding:8px 6px 10px;scroll-snap-type:x proximity;scrollbar-width:thin;touch-action:pan-x}.atlas-node{position:relative;left:auto;top:auto;transform:none;flex:0 0 88px;scroll-snap-align:start;min-height:100px;border:1px solid rgba(214,255,246,.09);background:rgba(0,39,43,.3);padding:8px 4px}.atlas-node img{width:52px;height:52px}.atlas-node[aria-pressed=true]{border-color:rgba(224,255,79,.6)}.atlas-detail:has(.atlas-detail-image){display:grid;grid-template-columns:84px minmax(0,1fr)}.atlas-detail-image{height:84px;margin-top:18px}.atlas-detail-copy{padding:16px 12px}.atlas-detail h4{font-size:22px}.atlas-purpose{font-size:12px}.atlas-io{margin:16px 0}.atlas-detail:has(.atlas-detail-image)>.atlas-detail-copy>.atlas-source{margin-left:-84px}.atlas-legend{gap:10px;padding-top:0}.atlas-desks{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.atlas-desk{padding:12px;min-height:124px}.atlas-growth-loop{grid-template-columns:repeat(3,minmax(0,1fr))}.atlas-path{flex-direction:column;gap:14px}.atlas-system{min-height:60px;padding:12px 14px}.atlas-system small{margin-top:4px}.atlas-path.chain .atlas-system:not(:last-child)::after{right:50%;top:auto;bottom:-15px;content:'↓'}.atlas-holds{grid-template-columns:1fr}.atlas-foot{padding:10px 16px;display:block}.atlas-foot span{display:block}.atlas-growth-header h4{font-size:22px}.atlas-map-caption small{display:inline;margin-left:6px}.atlas-stratum{padding:20px}.atlas-link-list{margin-top:12px}}
@container(max-width:700px){.atlas-heading{padding:20px 16px 14px;gap:8px}.atlas-heading h3{font-size:27px}.atlas-stamp{font-size:9px;padding:5px 8px}.atlas-tabs{padding:0 8px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr))}.atlas-tabs button{padding:0 4px;font-size:10px}.atlas-body{padding:12px}.atlas-layout{grid-template-columns:minmax(0,1fr)}.atlas-map{height:auto;background:none;overflow:visible;border:0}.atlas-map svg.atlas-rails{display:none}.atlas-family-group{margin-bottom:16px;min-width:0}.atlas-map-caption{position:static;margin:8px 0 12px;font-size:10px}.atlas-map-caption.operator{position:static}.atlas-family-nodes{display:flex;overflow-x:auto;gap:8px;padding:8px 6px 10px;scroll-snap-type:x proximity;scrollbar-width:thin;touch-action:pan-x}.atlas-node{position:relative;left:auto;top:auto;transform:none;flex:0 0 88px;scroll-snap-align:start;min-height:100px;border:1px solid rgba(214,255,246,.09);background:rgba(0,39,43,.3);padding:8px 4px}.atlas-node img{width:52px;height:52px}.atlas-node[aria-pressed=true]{border-color:rgba(224,255,79,.6)}.atlas-detail:has(.atlas-detail-image){display:grid;grid-template-columns:84px minmax(0,1fr)}.atlas-detail-image{height:84px;margin-top:18px}.atlas-detail-copy{padding:16px 12px}.atlas-detail h4{font-size:22px}.atlas-purpose{font-size:12px}.atlas-io{margin:16px 0}.atlas-detail:has(.atlas-detail-image)>.atlas-detail-copy>.atlas-source{margin-left:-84px}.atlas-legend{gap:10px;padding-top:0}.atlas-desks{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.atlas-desk{padding:12px;min-height:124px}.atlas-growth-loop{grid-template-columns:repeat(3,minmax(0,1fr))}.atlas-path{flex-direction:column;gap:14px}.atlas-system{min-height:60px;padding:12px 14px}.atlas-system small{margin-top:4px}.atlas-path.chain .atlas-system:not(:last-child)::after{right:50%;top:auto;bottom:-15px;content:'↓'}.atlas-holds{grid-template-columns:1fr}.atlas-foot{padding:10px 16px;display:block}.atlas-foot span{display:block}.atlas-growth-header h4{font-size:22px}.atlas-map-caption small{display:inline;margin-left:6px}.atlas-stratum{padding:20px}.atlas-link-list{margin-top:12px}}
@media(prefers-reduced-motion:no-preference){.atlas-node img,.atlas-system,.atlas-desk{transition:border-color .18s ease,box-shadow .18s ease}.atlas-node:hover img{box-shadow:0 0 0 4px rgba(214,255,246,.06)}}
@media(prefers-reduced-motion:reduce){.atlas *{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
@media print{.atlas{break-inside:avoid}.atlas-tabs,.atlas-link-action{display:none}.atlas-map{height:430px}.atlas-layout{grid-template-columns:2fr 1fr}.atlas-source{display:none}}
`;

const safeJson = (value: unknown) => JSON.stringify(value).replace(/</g, '\\u003c');
export const SYSTEM_ATLAS_BROWSER = String.raw`
const CambiumSystemAtlas = (() => {
  const model = ${safeJson(SYSTEM_ATLAS)};
  const portraits = ${safeJson(SYSTEM_ATLAS_PORTRAITS)};
  const views = ['organs','connections','growth','evidence'];
  const names = {organs:'Organs',connections:'System',growth:'Growth',evidence:'Evidence'};
  const esc = value => String(value == null ? '' : value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const chips = rows => '<div class="atlas-chips">' + rows.map(row => '<span>' + esc(row) + '</span>').join('') + '</div>';
  const source = (path, asset, selector, basis) => '<details class="atlas-source"><summary>Source binding</summary><code>' + esc(path) + '</code>' + (asset ? '<code>' + esc(asset) + '</code>' : '') + (selector ? '<code>' + esc(selector) + '</code>' : '') + '<p>' + (basis==='conceptual'?'Conceptual relationship · installed hop held':basis==='implementation'?'Implementation source · live receipt required':'Source contract · runtime receipt required') + '</p></details>';
  function organRelationships(id) {
    const rows=model.organLinks.filter(link=>link.from===id||link.to===id);
    const name=id=>model.organs.find(row=>row.id===id).name;
    return '<details class="atlas-source"><summary>'+rows.length+' source relationships</summary><div class="atlas-link-list">'+rows.map(link=>'<div class="atlas-link-item"><b>'+esc(name(link.from)+' → '+link.label+' → '+name(link.to))+'</b><small>'+esc(link.kind+' / '+link.basis)+'</small>'+source(link.source,null,link.selector,link.basis)+'</div>').join('')+'</div></details>';
  }
  function organDetail(row) {
    return '<aside class="atlas-detail" data-atlas-detail="' + esc(row.id) + '" aria-label="Selected organ contract"><img class="atlas-detail-image" src="' + portraits[row.id] + '" alt="' + esc(row.name) + ' reference concept" width="256" height="256"><div class="atlas-detail-copy"><div class="atlas-kicker">' + esc(row.family) + ' / ' + esc(row.verb) + '</div><h4>' + esc(row.name) + '</h4><p class="atlas-purpose">' + esc(row.purpose) + '</p><div class="atlas-io"><div><div class="atlas-io-label">01 / Receives</div>' + chips(row.inputs) + '</div><div><div class="atlas-io-label">02 / Produces</div>' + chips(row.outputs) + '</div></div><p class="atlas-boundary">' + esc(row.boundary) + '</p>' + organRelationships(row.id) + source(row.source,row.assetId) + '</div></aside>';
  }
  function organMap(selected) {
    const byId = Object.fromEntries(model.organs.map(row => [row.id,row]));
    const paths = model.organLinks.map(link => {
      const a=byId[link.from],b=byId[link.to];
      const x=a.x*9.2,y=a.y*5.2,tx=b.x*9.2,ty=b.y*5.2;
      const direction=tx>=x?1:-1;
      const curve = a.y===b.y ? 'M'+(x+32*direction)+' '+y+' C'+(x+85*direction)+' '+(y-10)+' '+(tx-85*direction)+' '+(ty+10)+' '+(tx-32*direction)+' '+ty : 'M'+x+' '+(y+32)+' C'+x+' '+((y+ty)/2)+' '+tx+' '+((y+ty)/2)+' '+tx+' '+(ty-32);
      return '<path data-kind="'+link.kind+'" class="'+(link.from===selected||link.to===selected?'is-selected':'')+'" d="'+curve+'"><title>'+esc(a.name+' → '+link.label+' → '+b.name)+'</title></path>';
    }).join('');
    return '<div class="atlas-map" aria-label="Two organ families"><svg class="atlas-rails" viewBox="0 0 920 520" preserveAspectRatio="none" aria-hidden="true">'+paths+'<path d="M32 319 H888" stroke-dasharray="2 7"/><text x="40" y="295">SCOPED EVIDENCE ↔ NEXT PROPOSAL</text></svg>'+model.families.map(family => '<div class="atlas-family-group"><div class="atlas-map-caption '+(family.id==='temperance'?'operator':'')+'">'+esc(family.name)+' / '+esc(family.detail)+'<small>'+esc(family.rule)+'</small></div><div class="atlas-family-nodes" role="group" aria-label="'+esc(family.name)+' organs">'+model.organs.filter(row=>row.family===family.id).map(row=>'<button type="button" class="atlas-node" style="--x:'+row.x+'%;--y:'+row.y+'%" data-atlas-organ="'+row.id+'" aria-pressed="'+(row.id===selected)+'" aria-label="Inspect '+row.name+'"><img loading="lazy" src="'+portraits[row.id]+'" alt="" width="64" height="64"><b>'+row.name+'</b><small>'+row.verb+'</small></button>').join('')+'</div></div>').join('')+'</div>';
  }
  const legend = () => '<div class="atlas-legend" aria-label="Connection types">'+['knowledge','execution','evidence','projection'].map(kind=>'<span data-kind="'+kind+'"><i aria-hidden="true"></i>'+kind+'</span>').join('')+'</div>';
  function systemPanel(selected) {
    const row = model.systems.find(row=>row.id===selected)||model.systems[0];
    const byId=Object.fromEntries(model.systems.map(row=>[row.id,row]));
    const group = (title,ids,chain) => '<section class="atlas-path-block"><div class="atlas-section-title">'+title+'</div><div class="atlas-path '+(chain?'chain':'')+'">'+ids.map(id=>'<button type="button" class="atlas-system" data-atlas-system="'+id+'" aria-pressed="'+(id===row.id)+'"><b>'+byId[id].name+'</b><small>'+byId[id].verb+'</small></button>').join('')+'</div></section>';
    const links=model.systemLinks.filter(link=>link.from===row.id||link.to===row.id);
    const detail='<aside class="atlas-detail"><div class="atlas-detail-copy"><div class="atlas-kicker">Source relationship</div><h4>'+row.name+'</h4><p class="atlas-purpose">'+row.owner+'</p><div class="atlas-link-list">'+links.map(link=>'<div class="atlas-link-item"><b>'+byId[link.from].name+' → '+byId[link.to].name+'</b><span>'+esc(link.label)+'</span><small>'+link.kind+'</small><p class="atlas-boundary">'+esc(link.boundary)+'</p>'+source(link.source,null,link.selector,link.basis)+'</div>').join('')+'</div>'+source(row.source)+'<button type="button" class="atlas-link-action" data-atlas-view="evidence">Follow the receipts</button></div></aside>';
    return '<div class="atlas-layout"><div class="atlas-paths">'+group('01 / ACCESS READ PATH · IDENTITY → ROLE → PROJECTION',['curious','access','plexus','fabric'],true)+group('02 / ACT · SIGNED CHOICE → ADMITTED WORK',['gate','d1','hermes'],true)+group('03 / OPTIONAL INFERENCE · SEPARATELY OWNED',['omniroute','broker'],false)+group('04 / DISTINCT OWNERS · SOURCES + EVIDENCE',['vault','github','proof','speculum'],false)+'<div class="atlas-path-note">Telegram has a separate signed founder/viewer read path.<br>Receipts ↳ bounded proposal ↳ fresh Gate<br>Read models and model transport cannot admit work.</div></div>'+detail+'</div>'+legend();
  }
  function growthPanel(selected) {
    const row=model.desks.find(row=>row.id===selected)||model.desks[0];
    return '<div class="atlas-growth-header"><img src="'+portraits.will+'" alt="Will reference concept" width="72" height="72"><div><div class="atlas-kicker">Will / six desks</div><h4>From source to a useful outcome.</h4><p>Roles use the existing execution owners.</p></div></div><div class="atlas-layout"><div><div class="atlas-desks">'+model.desks.map((desk,i)=>'<button type="button" class="atlas-desk" data-atlas-desk="'+desk.id+'" aria-pressed="'+(desk.id===row.id)+'"><span class="atlas-desk-number">0'+(i+1)+' / WILL</span><b>'+desk.name+'</b><small>'+desk.output+'</small></button>').join('')+'</div></div><aside class="atlas-detail"><div class="atlas-detail-copy"><div class="atlas-kicker">Role contract</div><h4>'+row.name+'</h4><p class="atlas-purpose">Execution contract · '+esc(row.owner)+'</p><p class="atlas-boundary">Goal / candidate · runtime assignment held</p><div class="atlas-io"><div><div class="atlas-io-label">Receives</div>'+chips([row.input])+'</div><div><div class="atlas-io-label">Produces</div>'+chips([row.output])+'</div><div><div class="atlas-io-label">Principal organ / Will desk</div>'+chips([row.principalOrgan,row.willDesk])+'</div><div><div class="atlas-io-label">Connected organs</div>'+chips(row.organs)+'</div><div><div class="atlas-io-label">Document owner</div>'+chips([row.documentOwner])+'</div></div><p class="atlas-boundary">A draft, edit or score never grants publishing permission.</p>'+source(row.source,null,row.selector,'contract')+'</div></aside></div><div class="atlas-growth-loop" aria-label="Governed growth loop">'+model.growthLoop.map((step,i)=>'<div class="atlas-growth-step" data-step="'+step.id+'"><b>0'+(i+1)+' / '+step.name+'</b><small>'+step.detail+'</small></div>').join('')+'</div><p class="atlas-path-note">Read inspects. Edit revises. Delivery needs its own owner gate.</p>';
  }
  function evidencePanel() {
    return '<div class="atlas-strata">'+model.receiptStrata.map((row,i)=>'<section class="atlas-stratum"><small>0'+(i+1)+' / DISTINCT RECEIPT</small><h4>'+row.name+'</h4><p>'+row.question+'</p><code>'+row.artifact+'</code></section>').join('')+'</div><div class="atlas-holds">'+model.holds.map(row=>'<section class="atlas-hold"><b>◇ '+row.name+' / held</b><p>'+row.detail+'</p>'+source(row.source)+'</section>').join('')+'</div><p class="atlas-retired">Historical only / '+model.retired.join(' · ')+'</p>'+source(model.retirementSource.path,null,model.retirementSource.selector,'contract');
  }
  function render(view,selected,rootId) {
    view=views.includes(view)?view:'organs';
    rootId=/^[a-z][a-z0-9-]{0,60}$/.test(rootId||'')?rootId:'system-atlas';
    const row=model.organs.find(row=>row.id===selected)||model.organs[0];
    const content=view==='organs'?'<div class="atlas-layout">'+organMap(row.id)+organDetail(row)+'</div>'+legend():view==='connections'?systemPanel(selected):view==='growth'?growthPanel(selected):evidencePanel();
    return '<section class="atlas" data-component="SystemAtlas" data-authority="read_only" data-evidence="source"><header class="atlas-heading"><div><div class="atlas-kicker">Cambium / System atlas</div><h3>One living system.</h3><p>Follow an input. Inspect an owner. Return with proof.</p></div><span class="atlas-stamp">◌ source view</span></header><div class="atlas-tabs" role="tablist" aria-label="System atlas views">'+views.map(v=>'<button type="button" role="tab" id="'+rootId+'-tab-'+v+'" data-atlas-view="'+v+'" aria-selected="'+(view===v)+'" aria-controls="'+rootId+'-panel" tabindex="'+(view===v?0:-1)+'">'+names[v]+'</button>').join('')+'</div><div class="atlas-body" id="'+rootId+'-panel" role="tabpanel" aria-labelledby="'+rootId+'-tab-'+view+'">'+content+'</div><footer class="atlas-foot"><span>11 organs / 2 families / 6 growth desks</span><span>Reference portraits · runtime evidence remains separate</span></footer></section>';
  }
  function mount(root,options) {
    if (!root) return;
    const initial=options||{};
    let view=views.includes(initial.view)?initial.view:'organs';
    let selected=typeof initial.selected==='string'?initial.selected:'genesis';
    function paint(focusSelector) {
      const offsets=[...root.querySelectorAll('.atlas-family-nodes')].map(group=>group.scrollLeft||0);
      root.innerHTML=render(view,selected,root.id);
      [...root.querySelectorAll('.atlas-family-nodes')].forEach((group,index)=>{group.scrollLeft=offsets[index]||0;});
      if(focusSelector){const target=root.querySelector(focusSelector);if(target){
        target.focus({preventScroll:true});
        const strip=target.closest('.atlas-family-nodes');
        if(strip&&typeof strip.getBoundingClientRect==='function'){
          const a=target.getBoundingClientRect(),b=strip.getBoundingClientRect();
          if(a.left<b.left)strip.scrollLeft+=a.left-b.left;
          else if(a.right>b.right)strip.scrollLeft+=a.right-b.right;
        }
      }}
    }
    paint();
    root.onclick=event=>{
      const target=event.target instanceof Element?event.target.closest('[data-atlas-view],[data-atlas-organ],[data-atlas-system],[data-atlas-desk]'):null;
      if(!target||!root.contains(target))return;
      if(target.dataset.atlasView){if(!views.includes(target.dataset.atlasView))return;view=target.dataset.atlasView;selected=view==='organs'?'genesis':view==='connections'?'curious':view==='growth'?'head-of-marketing':'';paint('[role="tab"][data-atlas-view="'+view+'"]');}
      else {const attr=target.dataset.atlasOrgan?'data-atlas-organ':target.dataset.atlasSystem?'data-atlas-system':'data-atlas-desk';const value=target.getAttribute(attr);const allowed=attr==='data-atlas-organ'?model.organs:attr==='data-atlas-system'?model.systems:model.desks;if(!allowed.some(row=>row.id===value))return;selected=value;paint('['+attr+'="'+value+'"]');}
    };
    root.onkeydown=event=>{
      const target=event.target;if(!(target instanceof Element))return;
      const attr=target.getAttribute('role')==='tab'?'data-atlas-view':target.hasAttribute('data-atlas-organ')?'data-atlas-organ':target.hasAttribute('data-atlas-system')?'data-atlas-system':target.hasAttribute('data-atlas-desk')?'data-atlas-desk':null;
      if(!attr||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(event.key))return;
      const targets=[...root.querySelectorAll((attr==='data-atlas-view'?'[role="tab"]':'')+'['+attr+']')];const index=targets.indexOf(target);if(index<0)return;
      event.preventDefault();event.stopPropagation();const next=event.key==='Home'?0:event.key==='End'?targets.length-1:(index+(['ArrowLeft','ArrowUp'].includes(event.key)?-1:1)+targets.length)%targets.length;
      targets[next].click();
    };
    return {getState:()=>({view,selected}),destroy:()=>{root.onclick=null;root.onkeydown=null;root.replaceChildren();}};
  }
  return Object.freeze({render,mount,model});
})();
`;

export const SYSTEM_ATLAS_STYLE = `<style>${SYSTEM_ATLAS_CSS}</style>`;
