import type { ScreenSpec } from './types.ts';

type RouteDraft = Omit<ScreenSpec, 'reference'>;

export const routeDrafts = [
  {
    id: 'home',
    taskId: 'T005',
    issue: 31,
    title: 'CAMBIUM',
    eyebrow: 'COMPANY COMPILER',
    mode: 'overview',
    exactLabels: ['CAMBIUM', 'COMPANY COMPILER', 'ARC X', '9/17', 'GENESIS', 'TASTE', 'BUILD', 'OPS', 'CORTEX'],
    description: 'The full 2.5D organ map: Genesis -> Taste -> Build -> Ops, with Cortex feeding every island.',
    defaultCamera: 'overview',
    panels: [
      { title: 'ARC X', value: '9/17', detail: 'current quest frontier', tone: 'signal' },
      { title: 'ACTIVE PATH', value: 'GENESIS -> TASTE', detail: 'packets moving toward Build', tone: 'mist' },
      { title: 'CORTEX', value: 'ONLINE', detail: 'memory rails feed every stage', tone: 'depth' },
    ],
  },
  {
    id: 'island-genesis',
    taskId: 'T006',
    issue: 32,
    title: 'GENESIS',
    eyebrow: 'BRAND DNA',
    mode: 'island',
    focusNode: 'genesis',
    exactLabels: ['GENESIS', 'BRAND DNA', 'IDEA IN', 'VARIABLES', 'ARC X'],
    description: 'Zoomed seed island where idea fragments become brand, copy, and visual variable groups.',
    defaultCamera: 'node',
    panels: [
      { title: 'IDEA IN', value: 'seed', detail: 'raw thoughtseed intake rail', tone: 'signal' },
      { title: 'brand_system', value: 'ready', detail: 'identity, positioning, voice', tone: 'mist' },
      { title: 'copy_system', value: 'ready', detail: 'headlines, CTA, proof', tone: 'mist' },
      { title: 'visual_system', value: 'ready', detail: 'palette, type, motion', tone: 'depth' },
    ],
  },
  {
    id: 'island-taste',
    taskId: 'T007',
    issue: 33,
    title: 'TASTE',
    eyebrow: 'TASTE BRIEF',
    mode: 'island',
    focusNode: 'taste',
    exactLabels: ['TASTE', 'TASTE BRIEF', 'REFERENCES', 'ACCEPTANCE', 'REROLL'],
    description: 'Reference retrieval, taste scoring, palette locks, acceptance gates, and reroll orbit.',
    defaultCamera: 'node',
    panels: [
      { title: 'REFERENCES', value: 'retrieved', detail: 'abstract swatches and contour tiles', tone: 'signal' },
      { title: 'TASTE BRIEF', value: 'locked', detail: 'brand-native visual direction', tone: 'mist' },
      { title: 'ACCEPTANCE', value: 'gated', detail: 'palette, motion, readability', tone: 'depth' },
      { title: 'REROLL', value: 'orbit', detail: 'same intent, better expression', tone: 'signal' },
    ],
  },
  {
    id: 'island-build',
    taskId: 'T008',
    issue: 34,
    title: 'BUILD',
    eyebrow: 'HANDS',
    mode: 'island',
    focusNode: 'build',
    exactLabels: ['BUILD', 'HANDS', 'ARTIFACT', 'GATES', 'PASS'],
    description: 'A workbench island where gates route into artifact slabs and validation markers.',
    defaultCamera: 'node',
    panels: [
      { title: 'HANDS', value: 'builder', detail: 'artifact assembly organ', tone: 'mist' },
      { title: 'GATES', value: '3 pass', detail: 'contract, motion, output', tone: 'signal' },
      { title: 'ARTIFACT', value: 'slab', detail: 'page, worker, asset packet', tone: 'depth' },
      { title: 'PASS', value: 'green', detail: 'validation marker visible', tone: 'signal' },
    ],
  },
  {
    id: 'island-ops',
    taskId: 'T009',
    issue: 35,
    title: 'OPS',
    eyebrow: 'WILL',
    mode: 'island',
    focusNode: 'ops',
    exactLabels: ['OPS', 'WILL', 'RUN LOOP', 'VIABILITY', 'LIVE'],
    description: 'The infinite-game loop: ingest, route, act, viability, learn, persist.',
    defaultCamera: 'node',
    panels: [
      { title: 'RUN LOOP', value: 'active', detail: 'pulse sits on viability turn', tone: 'signal' },
      { title: 'VIABILITY', value: 'inside', detail: 'solvency and coherence bounded', tone: 'mist' },
      { title: 'LIVE', value: 'heartbeat', detail: 'distribution feedback returns', tone: 'signal' },
      { title: 'WILL', value: 'operator', detail: 'business stays in motion', tone: 'depth' },
    ],
  },
  {
    id: 'island-cortex',
    taskId: 'T010',
    issue: 36,
    title: 'CORTEX',
    eyebrow: 'MEMORY',
    mode: 'island',
    focusNode: 'cortex',
    exactLabels: ['CORTEX', 'MEMORY', 'SEMANTIC', 'STRUCTURAL', 'RECALL'],
    description: 'Memory wheel with semantic and structural lanes, recall beams, and cross-stage links.',
    defaultCamera: 'node',
    panels: [
      { title: 'SEMANTIC', value: 'sqlite/vector', detail: 'nearest past situations', tone: 'mist' },
      { title: 'STRUCTURAL', value: 'codegraph', detail: 'symbol and call graph recall', tone: 'depth' },
      { title: 'RECALL', value: 'highlighted', detail: 'current path feeds Taste', tone: 'signal' },
      { title: 'MEMORY', value: 'compounds', detail: 'records survive across runs', tone: 'signal' },
    ],
  },
  {
    id: 'elements-settings',
    taskId: 'T011',
    issue: 37,
    title: 'ELEMENTS',
    eyebrow: 'SETTINGS',
    mode: 'settings',
    exactLabels: ['ELEMENTS', 'SETTINGS', 'PALETTE', 'MOTION', 'GLYPHS', 'REDUCED'],
    description: 'Design/operator controls for palette, motion, glyph family, rings, packets, labels, and reduced motion.',
    defaultCamera: 'flat',
    panels: [
      { title: 'PALETTE', value: 'locked', detail: 'five Cambium swatches', tone: 'signal' },
      { title: 'MOTION', value: '90s orbit', detail: 'transform and opacity only', tone: 'mist' },
      { title: 'GLYPHS', value: '5 organs', detail: 'abstract Coolshapes-ready metadata', tone: 'depth' },
      { title: 'REDUCED', value: 'on/off', detail: 'loops dead under media query', tone: 'signal' },
    ],
  },
  {
    id: 'visualizations',
    taskId: 'T012',
    issue: 38,
    title: 'VISUALIZATIONS',
    eyebrow: 'QUESTS · VIABILITY · MEMORY · FLOW',
    mode: 'visualizations',
    exactLabels: ['VISUALIZATIONS', 'QUESTS', 'VIABILITY', 'MEMORY', 'FLOW', '9/17'],
    description: 'Operator cockpit for quest rings, viability loop, memory graph, packet density, and stage handoff map.',
    defaultCamera: 'overview',
    panels: [
      { title: 'QUESTS', value: '9/17', detail: 'arc progress ring', tone: 'signal' },
      { title: 'VIABILITY', value: 'inside', detail: 'kernel loop stable', tone: 'mist' },
      { title: 'MEMORY', value: 'recall', detail: 'semantic + structural lanes', tone: 'depth' },
      { title: 'FLOW', value: 'dense', detail: 'packet rail throughput', tone: 'signal' },
    ],
  },
  {
    id: 'figma-components',
    taskId: 'T013',
    issue: 39,
    title: 'CAMBIUM DESIGN SYSTEM',
    eyebrow: 'TOKENS · GLYPHS · CONTROLS',
    mode: 'components',
    exactLabels: ['CAMBIUM DESIGN SYSTEM', 'TOKENS', 'GLYPHS', 'CONTROLS', 'STATES', 'PANELS'],
    description: 'Figma-style component inventory for tokens, glyphs, rings, rails, controls, states, and panels.',
    defaultCamera: 'flat',
    panels: [
      { title: 'TOKENS', value: '5 colors', detail: 'palette, opacity, type scale', tone: 'signal' },
      { title: 'GLYPHS', value: '5 nodes', detail: 'organ object specimens', tone: 'mist' },
      { title: 'CONTROLS', value: 'native', detail: 'toggle, slider, segmented', tone: 'depth' },
      { title: 'STATES', value: '6 rows', detail: 'idle, active, stale, warning, selected, reduced', tone: 'signal' },
      { title: 'PANELS', value: 'HUD set', detail: 'chips, labels, inspector surfaces', tone: 'mist' },
    ],
  },
  {
    id: 'asset-comparison',
    taskId: 'R3F-GE-ASSET-QA',
    issue: 52,
    title: 'ASSET QA',
    eyebrow: 'SOURCE · CURRENT · MASTER · REVIEW',
    mode: 'asset-comparison',
    exactLabels: ['ASSET QA', 'SOURCE', 'CURRENT', 'MASTER', 'REVIEW', 'HOLD', 'NOT PROMOTED', 'GENESIS', 'RAIL ARC'],
    description: 'Scene-native comparison bench for source plates, current runtime meshes, high-quality masters, and perceptual review before promotion.',
    defaultCamera: 'flat',
    panels: [
      { title: 'SOURCE', value: 'plates', detail: 'image-first art direction', tone: 'signal' },
      { title: 'CURRENT', value: 'runtime', detail: 'text-to-3D assets stay promoted', tone: 'mist' },
      { title: 'MASTER', value: 'candidate', detail: 'high-quality image-to-3D only', tone: 'depth' },
      { title: 'REVIEW', value: 'manual', detail: 'perceptual approval required', tone: 'signal' },
    ],
  },
] satisfies readonly RouteDraft[];

export const defaultScreenId = 'home';
export const screenOrder = routeDrafts.map((route) => route.id);
