export const FITCHECK_GOLDEN_PATH = {
  schema: 'cambium.fitcheck-golden-path.v1',
  version: 1,
  identity: {
    workId: 'sapling:fitcheck',
    parentTenant: 'cambium',
    name: 'Fitcheck',
    aliases: ['FitCheck', 'getfitcheck'],
    promotionState: 'supervised-branch',
    autonomyLabel: 'Supervised branch · not autonomous',
  },
  authority: {
    packet: 'planning evidence',
    runtime: 'D1 Goal Graph exact WorkObject anchor',
    proof: 'immutable execution receipt',
    nextIntent: 'proposal only until Goal Graph admission',
  },
  runtimeJoin: {
    evidenceStage: 'admitted',
    evidencedLabel: 'D1 WorkObject admitted',
    heldLabel: 'D1 admission held',
  },
  executionLadder: [
    { stage: 'mapped', authority: 'catalog plus reviewed mapping evidence', current: true },
    { stage: 'planned', authority: 'repository-owned Fitcheck packet', current: true },
    { stage: 'admitted', authority: 'D1 Goal Graph exact WorkObject anchor', current: false },
    { stage: 'pinned', authority: 'D1 loadout anchor plus loadout registry', current: false },
    { stage: 'executed', authority: 'fenced run plus terminal receipt', current: false },
    { stage: 'learned', authority: 'immutable foldback plus next-intent proposal', current: false },
  ],
  story: {
    arcTitle: 'Supervised Launch Hardening',
    vision: 'Fitcheck becomes the first proof-bound Cambium product branch that can move a Shopify fashion merchant from demo interest to supervised pilot.',
    icp: 'Shopify fashion brand founder or ecommerce operator who needs visual fit confidence before committing to a pilot.',
    currentFrontier: 'Supervised launch hardening: Shopify, Dodo, privacy, QA, outreach, and first merchant proof remain the live gates.',
    antiClaims: 'Do not claim app-store approval, conversion lift, unattended operation, or real merchant outcome until evidenced.',
  },
  feedbackLoop: [
    'intent',
    'plan',
    'gate',
    'dispatch',
    'execute',
    'receipt',
    'learn',
    'next intent',
  ],
  loop: {
    loopId: 'fitcheck-launch-gate-loop',
    title: 'Fitcheck launch gate loop',
    cadence: 'manual weekly until first merchant proof begins',
    objective: 'Move one Fitcheck launch blocker from blocked to evidenced or return a founder approval request.',
    metric: 'One gate changes status or one approval request is recorded per round.',
    boundaryColor: 'yellow',
    oneChangeRule: 'Select exactly one of Shopify QA, Dodo reservation env, privacy copy, outreach approval, or first merchant proof.',
    stopRule: 'Stop after 3 rounds, after first merchant proof is archived, or when missing credentials prevent the selected gate twice.',
  },
  organs: [
    { name: 'Genesis', owner: 'Fitcheck/HDILINT source docs', state: 'verified', role: 'brand DNA, copy, and visual system' },
    { name: 'Taste', owner: 'Cambium taste/audit loop', state: 'pending', role: 'landing, widget, copy, privacy, and render audit' },
    { name: 'Hands', owner: 'Fitcheck repositories', state: 'pending', role: 'bounded code and documentation patches' },
    { name: 'Will', owner: 'Snow Gloves OS / GTM routines', state: 'blocked', role: 'approved outreach, payment, and pilot reporting' },
    { name: 'Cortex', owner: 'Cambium/Cortex memory', state: 'pending', role: 'searchable branch lessons and proof summaries' },
  ],
  supportRails: [
    { name: 'Hermes', state: 'pending', role: 'policy-aware founder delivery and terminal foldback' },
    { name: 'Garden', state: 'blocked', role: 'branch-health cadence after the first pilot begins' },
  ],
  missions: [
    {
      missionId: 'fitcheck-shopify-qa',
      title: 'Run authenticated Shopify widget QA',
      type: 'proof',
      owner: 'founder/codex',
      gate: 'Credentials',
      proofRequired: 'screenshot plus widget event log',
      dispatchTarget: 'hermes',
    },
    {
      missionId: 'fitcheck-dodo-reservation',
      title: 'Wire Dodo reservation URL into production env',
      type: 'implementation',
      owner: 'founder/codex',
      gate: 'Payment',
      proofRequired: 'env receipt plus checkout smoke',
      dispatchTarget: 'cambium',
    },
    {
      missionId: 'fitcheck-outreach-approval',
      title: 'Approve first merchant outreach packet',
      type: 'approval',
      owner: 'founder',
      gate: 'Customer contact',
      proofRequired: 'approved copy plus target list note',
      dispatchTarget: 'plexus-agent-fabric',
    },
  ],
  kpis: [
    {
      kpiId: 'fitcheck-qualified-demo',
      label: 'Qualified merchant demo',
      survival: 'one qualified merchant completes demo or reservation flow',
      betterThanSurvival: 'one merchant schedules supervised pilot from the flow',
      currentState: 'pending',
    },
    {
      kpiId: 'fitcheck-first-merchant-proof',
      label: 'First merchant pilot proof',
      survival: 'pilot proof packet exists',
      betterThanSurvival: 'tracked widget events and customer proof fold into Cambium',
      currentState: 'blocked by access and approvals',
    },
  ],
  gates: [
    { gate: 'Human approvals', status: 'pending', requiredProof: 'Founder approval for Shopify submission, privacy/refund wording, real outreach, and public claims.' },
    { gate: 'Spend approvals', status: 'blocked', requiredProof: 'Explicit approval before live metered try-on generation.' },
    { gate: 'Privacy/legal', status: 'pending', requiredProof: 'Approved retention, deletion, no-training, consent, and refund language.' },
    { gate: 'Payment', status: 'blocked', requiredProof: 'Dodo payment/reservation link and production env proof.' },
    { gate: 'Customer contact', status: 'blocked', requiredProof: 'Approved outbound copy and first merchant target list.' },
    { gate: 'Public claims', status: 'blocked', requiredProof: 'No app-store approval or conversion lift claim until evidenced.' },
    { gate: 'Credentials', status: 'blocked', requiredProof: 'Shopify storefront/admin access and approved runtime action route.' },
  ],
  proofs: [
    {
      proofId: 'fitcheck-shopify-widget-proof',
      sourcePath: 'future Shopify QA screenshot and event receipt',
      validates: 'product-page try-on works under authenticated conditions',
      promotes: 'keeps supervised branch active; no autonomy promotion',
    },
    {
      proofId: 'fitcheck-payment-proof',
      sourcePath: 'Dodo/Vercel env receipt plus checkout smoke',
      validates: 'reservation/payment path is live enough for supervised pilot',
      promotes: 'unlocks customer-contact gate only after approval',
    },
    {
      proofId: 'fitcheck-first-merchant-packet',
      sourcePath: 'future first merchant proof packet',
      validates: 'real merchant pilot outcome',
      promotes: 'candidate for later autonomous review after app-action portability',
    },
  ],
  sources: {
    packet: 'docs/plans/product-branches/fitcheck.md',
    catalog: 'cambium.portfolio-catalog.v1',
    runtime: 'cambium.mission-fabric-projection.v1',
    foldback: 'cambium.hermes-execution-foldback.v1',
  },
} as const;

export type FitcheckGoldenPath = typeof FITCHECK_GOLDEN_PATH;
