import { compileOperationalPacketProjection } from './operational-packet-projection.ts';

export const FITCHECK_GOLDEN_PATH = compileOperationalPacketProjection({
  schema: 'cambium.fitcheck-golden-path.v1',
  version: 1,
  identity: {
    workId: 'sapling:fitcheck',
    kind: 'sapling',
    parentTenant: 'cambium',
    name: 'Fitcheck',
    aliases: ['FitCheck', 'getfitcheck'],
    promotionState: 'supervised-branch',
    autonomyLabel: 'Supervised branch · not autonomous',
  },
  authority: {
    packet: 'planning evidence',
    runtime: 'D1 Goal Graph exact WorkObject anchor',
    proof: 'immutable execution receipt',
    nextIntent: 'proposal only until Goal Graph admission',
  },
  authorityBoundaries: [
    { boundaryId: 'fitcheck-planning', domain: 'planning', authority: 'repository-owned Fitcheck packet', approvalRequired: false, mutationAllowed: true },
    { boundaryId: 'fitcheck-runtime', domain: 'runtime', authority: 'D1 Goal Graph exact WorkObject anchor', approvalRequired: true, mutationAllowed: false },
    { boundaryId: 'fitcheck-proof', domain: 'proof', authority: 'immutable terminal execution receipt', approvalRequired: false, mutationAllowed: false },
    { boundaryId: 'fitcheck-dispatch', domain: 'dispatch', authority: 'governed loadout plus signed approval', approvalRequired: true, mutationAllowed: false },
    { boundaryId: 'fitcheck-spend', domain: 'spend', authority: 'founder approval', approvalRequired: true, mutationAllowed: false },
    { boundaryId: 'fitcheck-external-mutation', domain: 'external-mutation', authority: 'founder approval and scoped runtime credential', approvalRequired: true, mutationAllowed: false },
    { boundaryId: 'fitcheck-next-intent', domain: 'next-intent', authority: 'receipt-derived proposal pending Goal Graph admission', approvalRequired: true, mutationAllowed: false },
  ],
  runtimeJoin: {
    evidenceStage: 'admitted',
    evidencedLabel: 'D1 WorkObject admitted',
    heldLabel: 'D1 admission held',
  },
  mappingAuthority: {
    state: 'readback-verified',
    bundleRef: 'docs/project-management/portfolio-mapping-receipts-batch-3.v1.json',
    preparedReceiptId: 'pmr_9de251ce89564f07f3e4c510',
    preparedR2Key: 'portfolio/thoughtseed/workobjects/sapling:fitcheck/mapping/pmr_9de251ce89564f07f3e4c510.json',
    receiptIssued: true,
    readbackVerified: true,
    issueAuthority: '2026-08-09 owner-approved R2 put plus byte-identical immutable readback; stored object sha256 0939d0dffcb30e93a3cb66502336ebcb9b8ef89e0f5b8c1fb171eb7a46430af5',
  },
  lifecycleLadder: [
    { stage: 'identified', authority: 'canonical catalog WorkObject identity', current: true, surface: 'intake' },
    { stage: 'systems-bound', authority: 'typed repository, WorkObject, and infrastructure topology', current: true, surface: 'intake' },
    { stage: 'mapped', authority: 'issued mapping receipt plus immutable readback', current: true, surface: 'execution' },
    { stage: 'mapping-receipt-verified', authority: 'issued mapping receipt plus immutable R2 readback', current: true, surface: 'intake' },
    { stage: 'planned', authority: 'repository-owned Fitcheck packet', current: true, surface: 'both' },
    { stage: 'd1-eligible', authority: 'mapping receipt readback plus reviewed operational packet; proposal unlocked but not applied', current: true, surface: 'intake' },
    { stage: 'admitted', authority: 'D1 Goal Graph exact WorkObject anchor', current: false, surface: 'execution' },
    { stage: 'pinned', authority: 'D1 loadout anchor plus loadout registry', current: false, surface: 'execution' },
    { stage: 'executed', authority: 'fenced run plus terminal receipt', current: false, surface: 'execution' },
    { stage: 'learned', authority: 'immutable foldback plus next-intent proposal', current: false, surface: 'execution' },
  ],
  repositoryComponents: [
    {
      componentId: 'fitcheck-landing',
      nameWithOwner: 'Sheshiyer/fitcheck-landing',
      immutableRepositoryId: 'R_kgDOSzF56w',
      roles: ['experience', 'frontend'],
      ownerWorkObjectId: 'sapling:fitcheck',
      planningAuthority: true,
      accessState: 'selected',
    },
    {
      componentId: 'hdilint-backend',
      nameWithOwner: 'Sheshiyer/HDILINT-backend-aleph',
      immutableRepositoryId: 'R_kgDOS4jKmg',
      roles: ['backend'],
      ownerWorkObjectId: 'program:hdilint',
      planningAuthority: false,
      accessState: 'verified',
    },
  ],
  workObjectDependencies: [
    {
      dependencyId: 'fitcheck-hdilint-backend',
      workObjectId: 'program:hdilint',
      kind: 'runtime',
      required: true,
      purpose: 'HDILINT owns and operates Fitcheck backend generation capabilities.',
    },
  ],
  infrastructureDependencies: [
    { dependencyId: 'fitcheck-vercel', kind: 'platform', name: 'Vercel', componentIds: ['fitcheck-landing'], accessState: 'verified', purpose: 'Hosts the Fitcheck landing and lead endpoint.' },
    { dependencyId: 'fitcheck-shopify', kind: 'commerce', name: 'Shopify', componentIds: ['fitcheck-landing', 'hdilint-backend'], accessState: 'held', purpose: 'Hosts the merchant product-page widget and authenticated QA surface.' },
    { dependencyId: 'fitcheck-aws-app-runner', kind: 'platform', name: 'AWS App Runner', componentIds: ['hdilint-backend'], ownerWorkObjectId: 'program:hdilint', accessState: 'verified', purpose: 'Runs the HDILINT backend used by Fitcheck.' },
    { dependencyId: 'fitcheck-dodo', kind: 'payments', name: 'Dodo Payments', componentIds: ['fitcheck-landing'], accessState: 'held', purpose: 'Provides the approval-gated reservation and pilot payment path.' },
    { dependencyId: 'fitcheck-r2', kind: 'storage', name: 'Cloudflare R2', componentIds: [], accessState: 'selected', purpose: 'Stores immutable mapping, execution, and foldback evidence.' },
    { dependencyId: 'fitcheck-cortex', kind: 'memory', name: 'Cortex', componentIds: [], accessState: 'selected', purpose: 'Indexes receipt-derived lessons and next-intent proposals.' },
  ],
  story: {
    arcTitle: 'Supervised Launch Hardening',
    vision: 'Fitcheck becomes the first proof-bound Cambium product branch that can move a Shopify fashion merchant from demo interest to supervised pilot.',
    icp: 'Shopify fashion brand founder or ecommerce operator who needs visual fit confidence before committing to a pilot.',
    currentFrontier: 'Supervised launch hardening: Shopify, Dodo, privacy, QA, outreach, and first merchant proof remain the live gates.',
    antiClaims: 'Do not claim app-store approval, conversion lift, unattended operation, or real merchant outcome until evidenced.',
  },
  feedbackLoop: [
    'intent',
    'plan',
    'gate',
    'dispatch',
    'execute',
    'receipt',
    'learn',
    'next intent',
  ],
  loop: {
    loopId: 'fitcheck-launch-gate-loop',
    title: 'Fitcheck launch gate loop',
    cadence: 'manual weekly until first merchant proof begins',
    objective: 'Move one Fitcheck launch blocker from blocked to evidenced or return a founder approval request.',
    metric: 'One gate changes status or one approval request is recorded per round.',
    boundaryColor: 'yellow',
    oneChangeRule: 'Select exactly one of Shopify QA, Dodo reservation env, privacy copy, outreach approval, or first merchant proof.',
    stopRule: 'Stop after 3 rounds, after first merchant proof is archived, or when missing credentials prevent the selected gate twice.',
  },
  organs: [
    { name: 'Genesis', owner: 'Fitcheck/HDILINT source docs', state: 'verified', role: 'brand DNA, copy, and visual system' },
    { name: 'Taste', owner: 'Cambium taste/audit loop', state: 'pending', role: 'landing, widget, copy, privacy, and render audit' },
    { name: 'Hands', owner: 'Fitcheck repositories', state: 'pending', role: 'bounded code and documentation patches' },
    { name: 'Will', owner: 'Snow Gloves OS / GTM routines', state: 'blocked', role: 'approved outreach, payment, and pilot reporting' },
    { name: 'Cortex', owner: 'Cambium/Cortex memory', state: 'pending', role: 'searchable branch lessons and proof summaries' },
  ],
  supportRails: [
    { name: 'Hermes', state: 'pending', role: 'policy-aware founder delivery and terminal foldback' },
    { name: 'Garden', state: 'blocked', role: 'branch-health cadence after the first pilot begins' },
  ],
  missions: [
    {
      missionId: 'fitcheck-shopify-qa',
      title: 'Run authenticated Shopify widget QA',
      type: 'proof',
      owner: 'founder/codex',
      gate: 'Credentials',
      proofRequired: 'screenshot plus widget event log',
      dispatchTarget: 'hermes',
    },
    {
      missionId: 'fitcheck-dodo-reservation',
      title: 'Wire Dodo reservation URL into production env',
      type: 'implementation',
      owner: 'founder/codex',
      gate: 'Payment',
      proofRequired: 'env receipt plus checkout smoke',
      dispatchTarget: 'cambium',
    },
    {
      missionId: 'fitcheck-outreach-approval',
      title: 'Approve first merchant outreach packet',
      type: 'approval',
      owner: 'founder',
      gate: 'Customer contact',
      proofRequired: 'approved copy plus target list note',
      dispatchTarget: 'plexus-agent-fabric',
    },
  ],
  kpis: [
    {
      kpiId: 'fitcheck-qualified-demo',
      label: 'Qualified merchant demo',
      survival: 'one qualified merchant completes demo or reservation flow',
      betterThanSurvival: 'one merchant schedules supervised pilot from the flow',
      currentState: 'pending',
    },
    {
      kpiId: 'fitcheck-first-merchant-proof',
      label: 'First merchant pilot proof',
      survival: 'pilot proof packet exists',
      betterThanSurvival: 'tracked widget events and customer proof fold into Cambium',
      currentState: 'blocked by access and approvals',
    },
  ],
  gates: [
    { gate: 'Human approvals', status: 'pending', requiredProof: 'Founder approval for Shopify submission, privacy/refund wording, real outreach, and public claims.' },
    { gate: 'Spend approvals', status: 'blocked', requiredProof: 'Explicit approval before live metered try-on generation.' },
    { gate: 'Privacy/legal', status: 'pending', requiredProof: 'Approved retention, deletion, no-training, consent, and refund language.' },
    { gate: 'Payment', status: 'blocked', requiredProof: 'Dodo payment/reservation link and production env proof.' },
    { gate: 'Customer contact', status: 'blocked', requiredProof: 'Approved outbound copy and first merchant target list.' },
    { gate: 'Public claims', status: 'blocked', requiredProof: 'No app-store approval or conversion lift claim until evidenced.' },
    { gate: 'Credentials', status: 'blocked', requiredProof: 'Shopify storefront/admin access and approved runtime action route.' },
  ],
  proofs: [
    {
      proofId: 'fitcheck-mapping-readback',
      sourcePath: 'R2 thoughtseed-vault portfolio/thoughtseed/workobjects/sapling:fitcheck/mapping/pmr_9de251ce89564f07f3e4c510.json',
      validates: 'Fitcheck repository mapping receipt was issued and read back byte-identically',
      promotes: 'unlocks the separate D1 Mission to Task proposal gate',
    },
    {
      proofId: 'fitcheck-shopify-widget-proof',
      sourcePath: 'future Shopify QA screenshot and event receipt',
      validates: 'product-page try-on works under authenticated conditions',
      promotes: 'keeps supervised branch active; no autonomy promotion',
    },
    {
      proofId: 'fitcheck-payment-proof',
      sourcePath: 'Dodo/Vercel env receipt plus checkout smoke',
      validates: 'reservation/payment path is live enough for supervised pilot',
      promotes: 'unlocks customer-contact gate only after approval',
    },
    {
      proofId: 'fitcheck-first-merchant-packet',
      sourcePath: 'future first merchant proof packet',
      validates: 'real merchant pilot outcome',
      promotes: 'candidate for later autonomous review after app-action portability',
    },
  ],
  sources: {
    packet: 'docs/plans/product-branches/fitcheck.md',
    catalog: 'cambium.portfolio-catalog.v1',
    runtime: 'cambium.mission-fabric-projection.v1',
    foldback: 'cambium.hermes-execution-foldback.v1',
  },
} as const);

export type FitcheckGoldenPath = typeof FITCHECK_GOLDEN_PATH;
