import { compileOperationalPacketProjection } from './operational-packet-projection.ts';

export const IVERIF_GOLDEN_PATH = compileOperationalPacketProjection({
  schema: 'cambium.iverif-golden-path.v1',
  version: 1,
  identity: {
    workId: 'sapling:iverif',
    kind: 'sapling',
    parentTenant: 'cambium',
    name: 'IVerif',
    aliases: ['IVerif', 'iverif-wiki'],
    promotionState: 'proof-only',
    autonomyLabel: 'Supervised branch · not autonomous',
  },
  authority: {
    packet: 'planning evidence',
    runtime: 'D1 Goal Graph exact WorkObject anchor',
    proof: 'immutable execution receipt',
    nextIntent: 'proposal only until Goal Graph admission',
  },
  authorityBoundaries: [
    { boundaryId: 'iverif-planning', domain: 'planning', authority: 'repository-owned IVerif packet', approvalRequired: false, mutationAllowed: true },
    { boundaryId: 'iverif-runtime', domain: 'runtime', authority: 'D1 Goal Graph exact WorkObject anchor', approvalRequired: true, mutationAllowed: false },
    { boundaryId: 'iverif-proof', domain: 'proof', authority: 'immutable terminal execution receipt', approvalRequired: false, mutationAllowed: false },
    { boundaryId: 'iverif-dispatch', domain: 'dispatch', authority: 'governed loadout plus signed approval', approvalRequired: true, mutationAllowed: false },
    { boundaryId: 'iverif-spend', domain: 'spend', authority: 'founder approval', approvalRequired: true, mutationAllowed: false },
    { boundaryId: 'iverif-external-mutation', domain: 'external-mutation', authority: 'founder approval and scoped runtime credential', approvalRequired: true, mutationAllowed: false },
    { boundaryId: 'iverif-next-intent', domain: 'next-intent', authority: 'receipt-derived proposal pending Goal Graph admission', approvalRequired: true, mutationAllowed: false },
  ],
  runtimeJoin: {
    evidenceStage: 'admitted',
    evidencedLabel: 'D1 WorkObject admitted',
    heldLabel: 'D1 admission held',
  },
  mappingAuthority: {
    state: 'readback-verified',
    bundleRef: 'docs/project-management/portfolio-mapping-receipts-batch-3.v1.json',
    preparedReceiptId: 'pmr_0866a507ab7b5e8ee16b6c64',
    preparedR2Key: 'portfolio/thoughtseed/workobjects/sapling:iverif/mapping/pmr_0866a507ab7b5e8ee16b6c64.json',
    receiptIssued: true,
    readbackVerified: true,
    issueAuthority: 'founder-direct-2026-08-11-activation-wave',
  },
  lifecycleLadder: [
    { stage: 'identified', authority: 'canonical catalog WorkObject identity', current: true, surface: 'intake' },
    { stage: 'systems-bound', authority: 'typed repository, WorkObject, and infrastructure topology', current: true, surface: 'intake' },
    { stage: 'mapped', authority: 'mapping receipt issued in activation wave 2026-08-11', current: true, surface: 'intake' },
    { stage: 'mapping-receipt-verified', authority: 'issued mapping receipt plus byte-identical R2 readback', current: true, surface: 'intake' },
    { stage: 'planned', authority: 'repository-owned IVerif packet', current: true, surface: 'both' },
    { stage: 'd1-eligible', authority: 'mapping receipt readback plus reviewed operational packet; proposal unlocked but not applied', current: true, surface: 'intake' },
    { stage: 'admitted', authority: 'D1 Goal Graph exact WorkObject anchor', current: false, surface: 'execution' },
    { stage: 'pinned', authority: 'D1 loadout anchor plus loadout registry', current: false, surface: 'execution' },
    { stage: 'executed', authority: 'fenced run plus terminal receipt', current: false, surface: 'execution' },
    { stage: 'learned', authority: 'immutable foldback plus next-intent proposal', current: false, surface: 'execution' },
  ],
  repositoryComponents: [
    {
      componentId: 'iverif-wiki',
      nameWithOwner: 'Sheshiyer/iverif-wiki',
      immutableRepositoryId: 'R_kgDOSwXJ7Q',
      roles: ['docs'],
      ownerWorkObjectId: 'sapling:iverif',
      planningAuthority: true,
      accessState: 'verified',
    },
  ],
  workObjectDependencies: [],
  infrastructureDependencies: [
    { dependencyId: 'iverif-r2', kind: 'storage', name: 'Cloudflare R2', componentIds: [], accessState: 'verified', purpose: 'Stores the immutable, readback-verified mapping receipt and later execution/foldback evidence.' },
    { dependencyId: 'iverif-cortex', kind: 'memory', name: 'Cortex', componentIds: [], accessState: 'held', purpose: 'Indexes receipt-derived lessons and next-intent proposals (unlocked after D1 admission).' },
  ],
  story: {
    arcTitle: 'Wiki Infrastructure Verification',
    vision: 'IVerif becomes the second governed Thoughtseed Sapling, proving a portfolio-mapped wiki identity can anchor a verified, admitted, and pinned D1 Task without collapsing planning, operational state, execution evidence, and learning into one ambiguous record.',
    icp: 'Thoughtseed founder or operator who needs verifiable WorkObject admission and loadout pinning from portfolio-mapped wiki infrastructure.',
    currentFrontier: 'Mapping receipt issued and read back; D1 anchor remains pending founder-signed Mini App Gate approval.',
    antiClaims: 'Do not claim tenant admission, loadout pin, or execution before issued mapping receipt readback and D1 CAS commit.',
  },
  feedbackLoop: [
    'intent',
    'plan',
    'gate',
    'dispatch',
    'execute',
    'receipt',
    'learn',
    'next intent',
  ],
  loop: {
    loopId: 'iverif-admission-gate-loop',
    title: 'IVerif admission gate loop',
    cadence: 'manual weekly until first D1 anchor commit begins',
    objective: 'Commit one founder-approved D1 Mission/Task anchor from the issued, byte-identical mapping receipt.',
    metric: 'One gate changes status (receipt issued → readback verified → D1 anchor committed) per round.',
    boundaryColor: 'yellow',
    oneChangeRule: 'Select exactly one: (a) issue prepared receipt + readback, (b) commit D1 anchor, (c) verify Mission Fabric edges.',
    stopRule: 'Stop after issuance + anchor are verified, or when the exact founder-approved receipt or D1 gate remains unavailable twice.',
  },
  organs: [
    { name: 'Genesis', owner: 'IVerif source docs', state: 'verified', role: 'identity, infrastructure, and operational boundary definition' },
    { name: 'Taste', owner: 'Cambium taste/audit loop', state: 'pending', role: 'packet, mapping, and D1 anchor review' },
    { name: 'Hands', owner: 'IVerif repository', state: 'pending', role: 'bounded code and documentation patches' },
    { name: 'Cortex', owner: 'Cambium/Cortex memory', state: 'pending', role: 'receipt-derived lessons and proof summaries' },
  ],
  supportRails: [
    { name: 'Hermes', state: 'blocked', role: 'policy-aware founder delivery and terminal foldback (after D1 admission)' },
  ],
  missions: [
    {
      missionId: 'iverif-wiki-activation',
      title: 'Issue mapping receipt and commit D1 WorkObject anchor',
      type: 'implementation',
      owner: 'founder/codex',
      gate: 'Human approvals',
      proofRequired: 'issued mapping receipt with byte-identical R2 readback plus D1 Mission Fabric contains/pins-loadout edges',
      dispatchTarget: 'cambium',
    },
  ],
  kpis: [
    {
      kpiId: 'iverif-mapping-readback',
      label: 'Mapping receipt issued and read back',
      survival: 'R2 object exists with contentDigest sha256:0866a507ab7b5e8ee16b6c6446a97a8f06ca1d5d98d0d35c67746ff799eb956a',
      betterThanSurvival: 'byte-identical readback validated through repository evidence file',
      currentState: 'issued-readback-verified',
    },
    {
      kpiId: 'iverif-d1-anchor',
      label: 'D1 Mission → Task anchor committed',
      survival: 'D1 Goal Graph contains a Task with workObjectId=sapling:iverif and pinnedLoadoutId=loadout:iverif-observer',
      betterThanSurvival: 'Mission Fabric proves contains edge + pins-loadout edge with zero anchor gaps',
      currentState: 'prepared-proposal-only',
    },
  ],
  gates: [
    { gate: 'Human approvals', status: 'pending', requiredProof: 'Founder-signed Mini App Gate approval for D1 CAS commit of the issued receipt.' },
    { gate: 'Credentials', status: 'verified', requiredProof: 'Byte-identical R2 readback of exact mapping evidence.' },
  ],
  proofs: [
    {
      proofId: 'iverif-mapping-readback',
      sourcePath: 'R2 thoughtseed-vault portfolio/thoughtseed/workobjects/sapling:iverif/mapping/pmr_0866a507ab7b5e8ee16b6c64.json',
      validates: 'IVerif mapping receipt was issued and read back byte-identically',
      promotes: 'unlocks the separate D1 Mission to Task proposal gate',
    },
    {
      proofId: 'iverif-d1-anchor',
      sourcePath: 'D1 Goal Graph Mission Fabric projection',
      validates: 'IVerif admitted with exact sapling:iverif Task anchor and loadout:iverif-observer pin',
      promotes: 'keeps supervised branch active; unlocks Hermes canary gate',
    },
  ],
  sources: {
    packet: 'docs/plans/product-branches/iverif.md',
    catalog: 'cambium.portfolio-catalog.v1',
    runtime: 'cambium.mission-fabric-projection.v1',
    foldback: 'cambium.hermes-execution-foldback.v1',
  },
} as const);

export type IverifGoldenPath = typeof IVERIF_GOLDEN_PATH;
