// Generated by scripts/audit-portfolio-miniapp-linkage.ts. Do not edit.
export const PORTFOLIO_LINKAGE_MANIFEST = {
  "schema": "cambium.portfolio-miniapp-linkage.v1",
  "catalogDigest": "sha256:311ead84a1e533f86e34f15a9d783e0350ac327d51d2c51c10d236d107ab96ca",
  "classificationDigest": "43630e6e65dfa78cd5c5e486b389308a8dede9d7bda012b400f4976107cdb309",
  "rootMapDigest": "e2abef8080c6ababab7a41e1803fa1eccc08b58a4dbf7876e586df78493bf351",
  "summary": {
    "totalWorkObjects": 72,
    "packetBackedStoryArcs": 5,
    "explicitStoryArcGaps": 67,
    "packetBackedQuestRows": 48,
    "missionDataGaps": 48,
    "activeOrganAssignments": 0
  },
  "rows": [
    {
      "workId": "branch:airdronauts-panorama-viewer-delivery",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "Airdronauts",
          "panaroma-webapp"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:ashwinsheth-marina-one-bangalore",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "ashwinsheth-group"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:ashwinsheth-marina-one-mumbai",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "ashwinsheth-group"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:axtech",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:axtech-erp",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:brightme",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:bwssb",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "bwssb"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:co-property",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "coproperty"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:dorix",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:earthy-munchy",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "earthy-munchy"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:harsh-truths",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "synchronized-universe-blog"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack-crm",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack-customer-portal",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack-estimate",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack-landing",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack-panel-app",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack-partner-portal",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack-proposal",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack-tooling",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack-veloren-cee-ai",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:heyzack-zackai",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "heyzack"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:insight-realtors-legal-advisors",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "insightreality"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:instal",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:kacima",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "kacima"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:klear-karma",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "klear-karma"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:kristudios",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "kristudios"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:mathis",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:newsense",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "newsense"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:parkarea",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "parkarea"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:pongotrasteros",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:safvr-landing-page",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "safvr"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:sandboxlife",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "sandboxlife"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:symphonics",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:thaleos",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:tirak",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "tirak"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:valmark",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "valmark"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:wattconnect",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:wegrid-ai",
      "classification": "client-branch",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "branch:wtfmedia",
      "classification": "client-branch",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "wtfmedia"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:cambium-operating-fabric",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "cambium"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:company-website",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "archived-thoughtseedlabs-website",
          "landingpage-ts-2026",
          "thoughtseedos-website"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:engineering-orchestration",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "skills"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:explee-capabilities",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "professional-headshot-suite",
          "readme-skill",
          "skills"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:hdilint",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "hdilint-backend-aleph"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:meristem-brand-system",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "brand-genesis",
          "brandmint",
          "brandmint-oracle-aleph",
          "meristem",
          "motionsites-export",
          "motionsites-skills",
          "thoughtseed-brand-atlas"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:operator-utilities",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "gram-cli",
          "raycast-extensions",
          "readme-skill",
          "reddit-cli"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:paperclip-retired",
      "classification": "internal-program",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:plexus",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "plexus-ts"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:skill-clusters",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "motionsites-skills",
          "professional-headshot-suite",
          "readme-skill",
          "skill-clusters",
          "skills"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:snow-gloves-os",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "snow-gloves-os"
        ]
      },
      "storyArc": {
        "state": "packet-backed",
        "arcId": "snow-gloves-os-will-organ-service-binding"
      },
      "quests": {
        "state": "packet-backed",
        "count": 7
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "packet-projected"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:teamforge-control-plane",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "team-forge-ts"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:temperance-hermes",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "hermes-aws-ts",
          "temperance-engine-landing-page",
          "temperance_engine",
          "thoughtseed-hermes"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:thoughtseed-brand-atlas",
      "classification": "internal-program",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "thoughtseed-brand-atlas"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "program:thoughtseed-vault",
      "classification": "internal-program",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:10869-space",
      "classification": "sapling",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:agentfount",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "agentfount"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:cambium",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "cambium"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:dlock",
      "classification": "sapling",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "packet-backed",
        "arcId": "dlock-resource-mapping-and-access-proof"
      },
      "quests": {
        "state": "packet-backed",
        "count": 7
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "packet-projected"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:effort-glyph",
      "classification": "sapling",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:fitcheck",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "fitcheck-landing",
          "fitcheck-wiki"
        ]
      },
      "storyArc": {
        "state": "packet-backed",
        "arcId": "fitcheck-supervised-launch-hardening"
      },
      "quests": {
        "state": "packet-backed",
        "count": 17
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "packet-projected"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:fmrl",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "fmrl",
          "fmrl-reactnative"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:hostscale",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "hostscale"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:iverif",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "iverif"
        ]
      },
      "storyArc": {
        "state": "packet-backed",
        "arcId": "iverif-claim-proof-separation"
      },
      "quests": {
        "state": "packet-backed",
        "count": 10
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "packet-projected"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:nimbus-gate",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "coproperty"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:rasa",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "monthlymealprep"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:seedforge",
      "classification": "sapling",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:vantyx",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "panaroma-webapp"
        ]
      },
      "storyArc": {
        "state": "packet-backed",
        "arcId": "vantyx-second-tenant-publish-proof"
      },
      "quests": {
        "state": "packet-backed",
        "count": 7
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "packet-projected"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:vibrasonix",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "vibrasonix"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:wanderfruit",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "coproperty"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "catalog-fields-present",
        "missingFields": []
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:whatslegal",
      "classification": "sapling",
      "filesystem": {
        "state": "explicit-folderless-gap",
        "folders": []
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    },
    {
      "workId": "sapling:whspr",
      "classification": "sapling",
      "filesystem": {
        "state": "mapped",
        "folders": [
          "whspr"
        ]
      },
      "storyArc": {
        "state": "explicit-unadmitted-gap",
        "arcId": null
      },
      "quests": {
        "state": "explicit-unadmitted-gap",
        "count": 0
      },
      "missionData": {
        "state": "mission-data-needed",
        "missingFields": [
          "blocker",
          "currentState",
          "desiredState",
          "goalGraphRef",
          "nextAction",
          "ownerId",
          "proofRequired",
          "reviewAt",
          "sourceDigest"
        ]
      },
      "organs": {
        "state": "workflow-available-unassigned",
        "linked": []
      },
      "miniApp": {
        "canopy": "catalog-visible",
        "mission": "explicit-gap"
      },
      "telegramTransport": "hermes-only"
    }
  ]
} as const;
