// Generated by scripts/generate-portfolio-root-map.mjs. Do not edit.
export const PORTFOLIO_ROOT_MAP_DIGEST = "20af5f2b3e194c67f1e19f9acc477cdfc51654876d75b310f4541998a8a576dc" as const;
export const PORTFOLIO_ROOTS = [
  {
    "portfolioId": "thoughtseed",
    "label": "Thoughtseed",
    "itemLabel": "WorkObject",
    "folderCount": 54,
    "infrastructure": [
      "_home-cleanup-2026-08-08",
      "cambium-authoritative",
      "openfang",
      "thoughtseed-labs",
      "website"
    ],
    "folders": [
      {
        "folder": "Airdronauts",
        "proposedKind": "client-branch",
        "accountId": "airdronauts-productions",
        "workIds": [
          "branch:airdronauts-panorama-viewer-delivery"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "agentfount",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:agentfount"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "archived-thoughtseedlabs-website",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:company-website"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "ashwinsheth-group",
        "proposedKind": "client-branch",
        "accountId": "ashwin-sheth-group",
        "workIds": [
          "branch:ashwinsheth-marina-one-mumbai",
          "branch:ashwinsheth-marina-one-bangalore"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "brand-genesis",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "brandmint",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "brandmint-oracle-aleph",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "bwssb",
        "proposedKind": "client-branch",
        "accountId": "spaceblanket-ai",
        "workIds": [
          "branch:bwssb"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "cambium",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:cambium",
          "program:cambium-operating-fabric"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "coproperty",
        "proposedKind": "client-branch",
        "accountId": "co-property",
        "workIds": [
          "branch:co-property",
          "sapling:nimbus-gate",
          "sapling:wanderfruit"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "earthy-munchy",
        "proposedKind": "client-branch",
        "accountId": "yamuna-foods",
        "workIds": [
          "branch:earthy-munchy"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "fitcheck-landing",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:fitcheck"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "fmrl",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:fmrl"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "fmrl-reactnative",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:fmrl"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "gram-cli",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:operator-utilities"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "hdilint-backend-aleph",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:hdilint"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "hermes-aws-ts",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:temperance-hermes"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "heyzack",
        "proposedKind": "client-branch",
        "accountId": "heyzack",
        "workIds": [
          "branch:heyzack",
          "branch:heyzack-zackai",
          "branch:heyzack-crm",
          "branch:heyzack-estimate",
          "branch:heyzack-partner-portal",
          "branch:heyzack-customer-portal",
          "branch:heyzack-panel-app",
          "branch:heyzack-landing",
          "branch:heyzack-tooling",
          "branch:heyzack-proposal",
          "branch:heyzack-veloren-cee-ai"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "hostscale",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:hostscale"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "insightreality",
        "proposedKind": "client-branch",
        "accountId": "insight-realtors-legal-advisors",
        "workIds": [
          "branch:insight-realtors-legal-advisors"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "iverif",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:iverif"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "kacima",
        "proposedKind": "client-branch",
        "accountId": "kacima",
        "workIds": [
          "branch:kacima"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "klear-karma",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [
          "sapling:klear-karma"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "kristudios",
        "proposedKind": "client-branch",
        "accountId": "kristudios",
        "workIds": [
          "branch:kristudios"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "landingpage-ts-2026",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:company-website"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "monthlymealprep",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:rasa"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "motionsites-export",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "motionsites-skills",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:meristem-brand-system",
          "program:skill-clusters"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "newsense",
        "proposedKind": "client-branch",
        "accountId": "newsense",
        "workIds": [
          "branch:newsense"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "panaroma-webapp",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [
          "sapling:vantyx",
          "branch:airdronauts-panorama-viewer-delivery"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "parkarea",
        "proposedKind": "client-branch",
        "accountId": "parkarea",
        "workIds": [
          "branch:parkarea",
          "sapling:parkarea"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "plexus-ts",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:plexus"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "plugins",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "mapping-proposal"
      },
      {
        "folder": "professional-headshot-suite",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:explee-capabilities",
          "program:skill-clusters"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "raycast-extensions",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:operator-utilities"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "reddit-cli",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:operator-utilities"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "readme-skill",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:explee-capabilities",
          "program:operator-utilities",
          "program:skill-clusters"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "sandboxlife",
        "proposedKind": "client-branch",
        "accountId": "valore-ventures",
        "workIds": [
          "branch:sandboxlife"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "safvr",
        "proposedKind": "client-branch",
        "accountId": "safvr",
        "workIds": [
          "branch:safvr-landing-page"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "skill-clusters",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:skill-clusters"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "skills",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:explee-capabilities",
          "program:engineering-orchestration",
          "program:skill-clusters"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "snow-gloves-os",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:snow-gloves-os"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "synchronized-universe-blog",
        "proposedKind": "client-branch",
        "accountId": "harshita",
        "workIds": [
          "branch:harsh-truths"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "team-forge-ts",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:teamforge-control-plane"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "temperance-engine-landing-page",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:temperance-hermes"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "thoughtseed-brand-atlas",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:thoughtseed-brand-atlas",
          "program:meristem-brand-system"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "thoughtseed-hermes",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:temperance-hermes"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "thoughtseedos-website",
        "proposedKind": "internal-program",
        "accountId": null,
        "workIds": [
          "program:company-website"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "tirak",
        "proposedKind": "client-branch",
        "accountId": "tirak",
        "workIds": [
          "branch:tirak",
          "sapling:tirak"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "valmark",
        "proposedKind": "client-branch",
        "accountId": "valmark",
        "workIds": [
          "branch:valmark"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "vibrasonix",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:vibrasonix"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "virtualtryon-3d",
        "proposedKind": "needs-review",
        "accountId": null,
        "workIds": [],
        "status": "empty-hold"
      },
      {
        "folder": "whspr",
        "proposedKind": "sapling",
        "accountId": null,
        "workIds": [
          "sapling:whspr"
        ],
        "status": "mapping-proposal"
      },
      {
        "folder": "wtfmedia",
        "proposedKind": "client-branch",
        "accountId": "wtf-podcast",
        "workIds": [
          "branch:wtfmedia"
        ],
        "status": "mapping-proposal"
      }
    ],
    "missingClientAccounts": [
      "axdis-group",
      "brightme",
      "dorix",
      "instal",
      "mathis",
      "pongotrasteros",
      "symphonics",
      "thaleos",
      "wattconnect",
      "wegrid"
    ]
  },
  {
    "portfolioId": "tryambakam-noesis",
    "label": "Tryambakam · Noesis",
    "itemLabel": "Project",
    "folderCount": 30,
    "folders": [
      {
        "folder": "10869x77",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "723",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "aleph1319xwebsite",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "aletheos-morphic-nexus",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "astrolens",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "astrolens-website",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "brand-docs-final",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "branding",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "bv-pip",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "content-engine",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "cosmo-align-workspace",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "dakm-philosophy",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "noesismirror-web-falseearth",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "paperclip-tn",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "phase-ion",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "polyhymnia",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "empty-hold"
      },
      {
        "folder": "selemene-engine",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "selemene-gw",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "serpentine-raising",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "somatic-canticles-book",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "somatic-canticles-mobile-app",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "somatic-canticles-webapp",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "synchronocities-blog",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "tpothp",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "tryambakam-space",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "twc-shell",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "urania-137",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "watchthisokay-stremio",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "witness-agents",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      },
      {
        "folder": "witness0s-webshore",
        "proposedKind": "project",
        "accountId": null,
        "workIds": [],
        "status": "awaiting-ingestion"
      }
    ],
    "infrastructure": [
      "selemene-engine-worktrees"
    ],
    "archiveContainer": "_archive",
    "archivedProjects": [
      "noesismirror-web",
      "sankalpa",
      "spatial-anubis-noesis",
      "witness-agents-intro-web"
    ]
  }
] as const;
