export interface OrganDefinition {
  id: string;
  name: string;
  body: 'cambium' | 'temperance';
  role: string;
  canDo: string[];
  cannotDo: string[];
  inputs: string[];
  outputs: string[];
  handsOffTo: string[];
  telegramTopics: string[];
  capabilityExamples: string[];
  boundary: string;
}

export const ORGAN_ATLAS: Record<string, OrganDefinition> = {
  // 5 Cambium Operating Organs
  'cambium.genesis': {
    id: 'cambium.genesis',
    name: 'Genesis',
    body: 'cambium',
    role: 'shape intent into a bounded brief or WorkObject seed',
    canDo: ['extract a finite objective', 'identify inputs and acceptance shape', 'emit a source-referenced brief'],
    cannotDo: ['invent missing authority', 'admit a Goal Graph mutation', 'approve launch or spend'],
    inputs: ['Vision/Mission', 'founder intent', 'product and audience facts'],
    outputs: ['brief', 'WorkObject seed', 'source receipt', 'missing-field repair request'],
    handsOffTo: ['cambium.taste', 'temperance.vestibule', 'cambium.hands'],
    telegramTopics: ['inbox', 'digests'],
    capabilityExamples: ['turn the current request into a bounded brief', 'show missing inputs before build work begins'],
    boundary: 'Does not become company doctrine, publish, spend, or invent missing identity fields.',
  },
  'cambium.taste': {
    id: 'cambium.taste',
    name: 'Taste',
    body: 'cambium',
    role: 'judge resonance, quality, and brand conformance',
    canDo: ['compare against exemplars', 'produce a verdict with acceptance checks', 'request a reroll or refinement'],
    cannotDo: ['grant consent', 'authorize public/client sending', 'permit model spend'],
    inputs: ['Genesis DNA', 'draft or artifact', 'audience context', 'taste brief'],
    outputs: ['taste verdict', 'quality constraints', 'acceptance checklist', 'reroll request'],
    handsOffTo: ['cambium.hands', 'cambium.will', 'cambium.cortex'],
    telegramTopics: ['digests', 'dev'],
    capabilityExamples: ['explain why the current artifact is weak', 'surface the next quality correction'],
    boundary: 'Conscience and evaluator, not an autonomous publisher, commercial approver, or source of doctrine.',
  },
  'cambium.hands': {
    id: 'cambium.hands',
    name: 'Hands',
    body: 'cambium',
    role: 'turn an admitted phase contract into bounded implementation',
    canDo: ['execute a scoped change', 'attach verification evidence', 'prepare a reversible artifact'],
    cannotDo: ['skip admission', 'merge or deploy without the applicable gate', 'treat transport success as semantic proof'],
    inputs: ['ISA/GSD acceptance', 'phase contract', 'Taste verdict', 'tool and model route'],
    outputs: ['source change', 'test result', 'rendered artifact', 'verification receipt'],
    handsOffTo: ['cambium.will', 'cambium.cortex', 'hermes.delivery'],
    telegramTopics: ['dev', 'agent_ops'],
    capabilityExamples: ['prepare the next bounded build step', 'show the exact verification still missing'],
    boundary: 'Is not a skill dump, planner, doctrine owner, or license to mutate an unadmitted project.',
  },
  'cambium.will': {
    id: 'cambium.will',
    name: 'Will',
    body: 'cambium',
    role: 'interpret evidence and prepare governed movement',
    canDo: ['route to the correct desk or role', 'prepare a draft or queue item', 'surface a decision with its gate'],
    cannotDo: ['become a sixth organ', 'publish directly', 'override founder or system authority'],
    inputs: ['Genesis brief', 'Taste verdict', 'Hands receipt', 'Cortex retrieval', 'delivery policy'],
    outputs: ['recommendation', 'handoff', 'ActionRequest proposal', 'founder decision packet'],
    handsOffTo: ['founder gate', 'hermes.delivery', 'cambium.hands'],
    telegramTopics: ['digests', 'alerts', 'clients'],
    capabilityExamples: ['explain the next governed move', 'show which approval boundary is active'],
    boundary: 'Does not auto-post, create a second product, bypass approval, or replace a tenant systems of record.',
  },
  'cambium.cortex': {
    id: 'cambium.cortex',
    name: 'Cortex',
    body: 'cambium',
    role: 'retrieve and preserve source-linked derived memory',
    canDo: ['retrieve relevant evidence', 'fold back redacted lessons', 'show provenance and source version'],
    cannotDo: ['rewrite current truth', 'mutate the Goal Graph', 'promote a lesson into policy automatically'],
    inputs: ['source artifacts', 'receipts', 'redacted learning signals', 'query context'],
    outputs: ['retrieval context', 'provenance bundle', 'learning proposal', 'staleness warning'],
    handsOffTo: ['temperance.nutrix', 'cambium.will', 'founder review'],
    telegramTopics: ['digests', 'adytum'],
    capabilityExamples: ['retrieve the prior evidence relevant to this task', 'show what changed since the last receipt'],
    boundary: 'Is not doctrine, D1 authority, a vault dump, or a substitute for source verification.',
  },

  // 6 Temperance Cognitive Lifecycle Organs
  'temperance.vestibule': {
    id: 'temperance.vestibule',
    name: 'Vestibule',
    body: 'temperance',
    role: 'orient a new session from federated memory and current project state',
    canDo: ['read current phase and routes', 'emit read-only orientation', 'suggest the next safe context load'],
    cannotDo: ['write D1', 'send Telegram through Bot API', 'merge or deploy'],
    inputs: ['session start', 'federated memory', 'project state', 'route manifest'],
    outputs: ['orientation', 'NOESIS status', 'context suggestions'],
    handsOffTo: ['temperance.adytum', 'temperance.praeceptor', 'cambium.genesis'],
    telegramTopics: ['adytum', 'hermes'],
    capabilityExamples: ['orient the current session', 'show which project and phase are active'],
    boundary: 'Read-only; never plans, claims a lane, writes memory, mutates routing, or gates execution.',
  },
  'temperance.adytum': {
    id: 'temperance.adytum',
    name: 'Adytum',
    body: 'temperance',
    role: 'compose read-only context across the four sovereign planes',
    canDo: ['produce a bounded next-action card', 'compare Cambium and Temperance context', 'point to the next reviewable move'],
    cannotDo: ['write D1', 'call Telegram Bot API', 'merge source planes or claim deployment proof'],
    inputs: ['Vestibule output', 'vault truth', 'Temperance signals', 'Hermes projection', 'Cambium receipts'],
    outputs: ['thoughtseed.telegram-next-action.v1', 'read-only synthesis', 'no-action result'],
    handsOffTo: ['founder review', 'cambium.will', 'hermes.delivery'],
    telegramTopics: ['adytum', 'digests'],
    capabilityExamples: ['explain the interlinked next action', 'show where a source-backed context seam is waiting'],
    boundary: 'Never merges memory planes, writes memory, calls Bot API, or writes the Goal Graph.',
  },
  'temperance.nutrix': {
    id: 'temperance.nutrix',
    name: 'Nutrix',
    body: 'temperance',
    role: 'harvest session learning into the local signal plane',
    canDo: ['extract a redacted lesson', 'record operator feedback', 'propose a future improvement'],
    cannotDo: ['rewrite source truth', 'change live routing', 'turn a signal into a task without admission'],
    inputs: ['session end', 'receipts', 'operator feedback', 'failure patterns'],
    outputs: ['nutrix.signal.v1', 'learning proposal', 'feedback summary'],
    handsOffTo: ['cambium.cortex', 'temperance.circulator', 'temperance.praeceptor'],
    telegramTopics: ['digests', 'adytum'],
    capabilityExamples: ['show the lesson from the latest run', 'identify a repeated friction worth review'],
    boundary: 'Does not judge, rewrite the decision ledger, mutate router state, or auto-write vault truth.',
  },
  'temperance.auspex': {
    id: 'temperance.auspex',
    name: 'Auspex',
    body: 'temperance',
    role: 'probe local substrate health and prepare scoped healing',
    canDo: ['check manifest/VAS/Athanor/OmniRoute health', 'classify a failure', 'prepare a scoped heal recommendation'],
    cannotDo: ['claim healthy runtime from source evidence', 'heal outside scope', 'change credentials or production state'],
    inputs: ['scheduled probe', 'health endpoints', 'runtime receipts', 'failure symptoms'],
    outputs: ['health finding', 'route eligibility', 'scoped heal proposal'],
    handsOffTo: ['temperance.circulator', 'cambium.will', 'founder gate'],
    telegramTopics: ['agent_ops', 'alerts'],
    capabilityExamples: ['show which substrate check failed', 'separate bridge health from provider health'],
    boundary: 'Never loops indefinitely, directly mutates provider connections, or claims application success.',
  },
  'temperance.circulator': {
    id: 'temperance.circulator',
    name: 'Circulator',
    body: 'temperance',
    role: 'assemble a periodic recommendation digest',
    canDo: ['summarize recurring signals', 'rank reviewable recommendations', 'surface unresolved loops'],
    cannotDo: ['auto-approve recommendations', 'write D1', 'send client or public updates'],
    inputs: ['Cortex retrieval', 'Nutrix signals', 'Auspex findings', 'delivery history'],
    outputs: ['weekly digest', 'ranked recommendations', 'review queue'],
    handsOffTo: ['founder decision', 'cambium.will', 'hermes.delivery'],
    telegramTopics: ['digests'],
    capabilityExamples: ['show the highest-leverage unresolved loop', 'summarize what deserves founder review'],
    boundary: 'Never flips flags, mutates provider state, auto-promotes skills, or becomes a planner.',
  },
  'temperance.praeceptor': {
    id: 'temperance.praeceptor',
    name: 'Praeceptor',
    body: 'temperance',
    role: 'prepare a small daily advisory set',
    canDo: ['draft up to five suggestions', 'connect evidence to a possible next step', 'hold a recommendation for review'],
    cannotDo: ['execute the suggestion', 'change router configuration', 'bypass the active task or approval gate'],
    inputs: ['Cortex/Nutrix/Auspex substrate', 'current phase', 'task state', 'Taste boundaries'],
    outputs: ['daily advisor draft', 'bounded suggestion', 'hold reason'],
    handsOffTo: ['temperance.circulator', 'founder review', 'cambium.hands'],
    telegramTopics: ['digests', 'alerts'],
    capabilityExamples: ['suggest the next safe task-aware move', 'explain why the suggestion is held'],
    boundary: 'Never edits live catalogs, auto-promotes a skill, flips a route, or rewrites project doctrine.',
  },
};
